//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.ServicioPerfil
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PerfilTransaccion", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts")]
    public partial class PerfilTransaccion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Auditoria AuditoriaField;

        private int IdRolField;

        private Komatsu.Core.Seguridad.ServicioPerfil.ListaUsuarioRol ListaUsuarioRolField;

        private int OptionField;

        private string RespuestaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioPerfil.Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioPerfil.ListaUsuarioRol ListaUsuarioRol
        {
            get
            {
                return this.ListaUsuarioRolField;
            }
            set
            {
                this.ListaUsuarioRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Option
        {
            get
            {
                return this.OptionField;
            }
            set
            {
                this.OptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Auditoria", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts")]
    public partial class Auditoria : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime FechaHoraField;

        private string HostNameField;

        private string IPField;

        private int IdAccionField;

        private int IdAuditoriaField;

        private string IdReferenciaField;

        private int IdTablaReferenciaField;

        private string IdTipoAccionField;

        private int IdUsuarioField;

        private string ObservacionesField;

        private string UserNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora
        {
            get
            {
                return this.FechaHoraField;
            }
            set
            {
                this.FechaHoraField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostName
        {
            get
            {
                return this.HostNameField;
            }
            set
            {
                this.HostNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccion
        {
            get
            {
                return this.IdAccionField;
            }
            set
            {
                this.IdAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAuditoria
        {
            get
            {
                return this.IdAuditoriaField;
            }
            set
            {
                this.IdAuditoriaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdReferencia
        {
            get
            {
                return this.IdReferenciaField;
            }
            set
            {
                this.IdReferenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTablaReferencia
        {
            get
            {
                return this.IdTablaReferenciaField;
            }
            set
            {
                this.IdTablaReferenciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTipoAccion
        {
            get
            {
                return this.IdTipoAccionField;
            }
            set
            {
                this.IdTipoAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaUsuarioRol", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "UsuarioRol")]
    public class ListaUsuarioRol : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.UsuarioRol>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UsuarioRol", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class UsuarioRol : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdUsuarioField;

        private int IdRolField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Usuario UsuarioField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Rol RolField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Rol Rol
        {
            get
            {
                return this.RolField;
            }
            set
            {
                this.RolField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Usuario", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdUsuarioField;

        private string CodigoEmpField;

        private string EmailCoorporativoField;

        private string NombreApellidoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        private string UserNameField;

        private Komatsu.Core.Seguridad.ServicioPerfil.UsuarioTipo UsuarioTipoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.ListaRol ListaRolField;

        private string ContentStyleField;

        private string SexoField;

        private string CorreoField;

        private string CorreoBoletaField;

        private string DireccionField;

        private System.DateTime FechaNacimientoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Empresa EmpresaField;

        private string DNIField;

        private int IdSociedadField;

        private string SociedadDescripcionCortaField;

        private int IdAreaBUField;

        private string AreaBUDescripcionCortaField;

        private int IdCargoField;

        private string CargoDescripcionCortaField;

        private int IdAplicacionField;

        private int IdComiteField;

        private int ActivoField;

        private string PasswordField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Cargo CargoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Area AreaField;

        private string IdAreasField;

        private bool CambiarPasswordField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Empresa EmpresaRelacionadaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string CodigoEmp
        {
            get
            {
                return this.CodigoEmpField;
            }
            set
            {
                this.CodigoEmpField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string EmailCoorporativo
        {
            get
            {
                return this.EmailCoorporativoField;
            }
            set
            {
                this.EmailCoorporativoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string NombreApellido
        {
            get
            {
                return this.NombreApellidoField;
            }
            set
            {
                this.NombreApellidoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public Komatsu.Core.Seguridad.ServicioPerfil.UsuarioTipo UsuarioTipo
        {
            get
            {
                return this.UsuarioTipoField;
            }
            set
            {
                this.UsuarioTipoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public Komatsu.Core.Seguridad.ServicioPerfil.ListaRol ListaRol
        {
            get
            {
                return this.ListaRolField;
            }
            set
            {
                this.ListaRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string ContentStyle
        {
            get
            {
                return this.ContentStyleField;
            }
            set
            {
                this.ContentStyleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public string CorreoBoleta
        {
            get
            {
                return this.CorreoBoletaField;
            }
            set
            {
                this.CorreoBoletaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 14)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 15)]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 16)]
        public int IdSociedad
        {
            get
            {
                return this.IdSociedadField;
            }
            set
            {
                this.IdSociedadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 17)]
        public string SociedadDescripcionCorta
        {
            get
            {
                return this.SociedadDescripcionCortaField;
            }
            set
            {
                this.SociedadDescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 18)]
        public int IdAreaBU
        {
            get
            {
                return this.IdAreaBUField;
            }
            set
            {
                this.IdAreaBUField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 19)]
        public string AreaBUDescripcionCorta
        {
            get
            {
                return this.AreaBUDescripcionCortaField;
            }
            set
            {
                this.AreaBUDescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 20)]
        public int IdCargo
        {
            get
            {
                return this.IdCargoField;
            }
            set
            {
                this.IdCargoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 21)]
        public string CargoDescripcionCorta
        {
            get
            {
                return this.CargoDescripcionCortaField;
            }
            set
            {
                this.CargoDescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 22)]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 23)]
        public int IdComite
        {
            get
            {
                return this.IdComiteField;
            }
            set
            {
                this.IdComiteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 24)]
        public int Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 25)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 26)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Cargo Cargo
        {
            get
            {
                return this.CargoField;
            }
            set
            {
                this.CargoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 27)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Area Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 28)]
        public string IdAreas
        {
            get
            {
                return this.IdAreasField;
            }
            set
            {
                this.IdAreasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 29)]
        public bool CambiarPassword
        {
            get
            {
                return this.CambiarPasswordField;
            }
            set
            {
                this.CambiarPasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 30)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Empresa EmpresaRelacionada
        {
            get
            {
                return this.EmpresaRelacionadaField;
            }
            set
            {
                this.EmpresaRelacionadaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Rol", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdRolField;

        private bool SiSuperAdmiField;

        private string NombreField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        private bool SiRangoField;

        private System.DateTime FechaInicioField;

        private System.DateTime FechaFinField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Aplicacion AplicacionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Usuario UsuarioField;

        private int IdCentroAtencionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.ListaOperacion ListaOperacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiSuperAdmi
        {
            get
            {
                return this.SiSuperAdmiField;
            }
            set
            {
                this.SiSuperAdmiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool SiRango
        {
            get
            {
                return this.SiRangoField;
            }
            set
            {
                this.SiRangoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public System.DateTime FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Aplicacion Aplicacion
        {
            get
            {
                return this.AplicacionField;
            }
            set
            {
                this.AplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public int IdCentroAtencion
        {
            get
            {
                return this.IdCentroAtencionField;
            }
            set
            {
                this.IdCentroAtencionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public Komatsu.Core.Seguridad.ServicioPerfil.ListaOperacion ListaOperacion
        {
            get
            {
                return this.ListaOperacionField;
            }
            set
            {
                this.ListaOperacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Estado", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdEstadoField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UsuarioTipo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class UsuarioTipo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdUsuarioTipoField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioTipo
        {
            get
            {
                return this.IdUsuarioTipoField;
            }
            set
            {
                this.IdUsuarioTipoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empresa", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdEmpresaField;

        private string NombreField;

        private string AbreviaturaField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        private bool CheckField;

        private string IdsEmpresaField;

        private string CodigoEmpresaField;

        private string ContentStyleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Abreviatura
        {
            get
            {
                return this.AbreviaturaField;
            }
            set
            {
                this.AbreviaturaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string IdsEmpresa
        {
            get
            {
                return this.IdsEmpresaField;
            }
            set
            {
                this.IdsEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public string CodigoEmpresa
        {
            get
            {
                return this.CodigoEmpresaField;
            }
            set
            {
                this.CodigoEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string ContentStyle
        {
            get
            {
                return this.ContentStyleField;
            }
            set
            {
                this.ContentStyleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Cargo", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts.Gene" +
        "ratedCode")]
    public partial class Cargo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescripcionField;

        private int EstadoField;

        private int IdCargoField;

        private string NombreCargoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCargo
        {
            get
            {
                return this.IdCargoField;
            }
            set
            {
                this.IdCargoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCargo
        {
            get
            {
                return this.NombreCargoField;
            }
            set
            {
                this.NombreCargoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Area", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts")]
    public partial class Area : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CorrelativoField;

        private string DescripcionField;

        private int EstadoField;

        private int IdAreaField;

        private bool IsCheckedField;

        private bool IsEnableCheckField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correlativo
        {
            get
            {
                return this.CorrelativoField;
            }
            set
            {
                this.CorrelativoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea
        {
            get
            {
                return this.IdAreaField;
            }
            set
            {
                this.IdAreaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChecked
        {
            get
            {
                return this.IsCheckedField;
            }
            set
            {
                this.IsCheckedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnableCheck
        {
            get
            {
                return this.IsEnableCheckField;
            }
            set
            {
                this.IsEnableCheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaRol", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Rol")]
    public class ListaRol : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.Rol>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Aplicacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Aplicacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAplicacionField;

        private string NombreField;

        private string DescripcionField;

        private string UrlField;

        private Komatsu.Core.Seguridad.ServicioPerfil.ListaAplicacionTraductor ListaAplicacionTraductorField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Empresa EmpresaField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        private bool CheckField;

        private string IdsAplicacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioPerfil.ListaAplicacionTraductor ListaAplicacionTraductor
        {
            get
            {
                return this.ListaAplicacionTraductorField;
            }
            set
            {
                this.ListaAplicacionTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string IdsAplicacion
        {
            get
            {
                return this.IdsAplicacionField;
            }
            set
            {
                this.IdsAplicacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaOperacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Operacion")]
    public class ListaOperacion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.Operacion>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaAplicacionTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "AplicacionTraductor")]
    public class ListaAplicacionTraductor : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.AplicacionTraductor>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AplicacionTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class AplicacionTraductor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAplicacionTraductorField;

        private int IdLenguajeField;

        private int IdAplicacionField;

        private string NombreField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Lenguaje LenguajeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAplicacionTraductor
        {
            get
            {
                return this.IdAplicacionTraductorField;
            }
            set
            {
                this.IdAplicacionTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Lenguaje Lenguaje
        {
            get
            {
                return this.LenguajeField;
            }
            set
            {
                this.LenguajeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Lenguaje", Namespace = "http://Komatsu.SSCA.Seguridad.Model/2013/DCKomatsuSeguridad")]
    public partial class Lenguaje : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdLenguajeField;

        private string NombreField;

        private string DiminutivoField;

        private bool ActivoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Diminutivo
        {
            get
            {
                return this.DiminutivoField;
            }
            set
            {
                this.DiminutivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Operacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Operacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdOperacionField;

        private string DescripcionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOperacion
        {
            get
            {
                return this.IdOperacionField;
            }
            set
            {
                this.IdOperacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaTreeviewHierarchyObject", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "TreeviewHierarchyObject")]
    public class ListaTreeviewHierarchyObject : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.TreeviewHierarchyObject>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TreeviewHierarchyObject", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class TreeviewHierarchyObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdField;

        private string NombreField;

        private int IdPadreField;

        private int NivelField;

        private int NivelPaginaField;

        private int IdPaginaPadreField;

        private bool CheckField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int IdPadre
        {
            get
            {
                return this.IdPadreField;
            }
            set
            {
                this.IdPadreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public int Nivel
        {
            get
            {
                return this.NivelField;
            }
            set
            {
                this.NivelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public int NivelPagina
        {
            get
            {
                return this.NivelPaginaField;
            }
            set
            {
                this.NivelPaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public int IdPaginaPadre
        {
            get
            {
                return this.IdPaginaPadreField;
            }
            set
            {
                this.IdPaginaPadreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPermisoPerfil", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "PermisoPerfil")]
    public class ListaPermisoPerfil : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.PermisoPerfil>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PermisoPerfil", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class PermisoPerfil : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdPermisoPerfilField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Empresa EmpresaField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Aplicacion AplicacionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Modulo ModuloField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Pagina PaginaField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Accion AccionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Rol RolField;

        private int IdEmpresaField;

        private int IdAplicacionField;

        private int IdModuloField;

        private int IdPaginaField;

        private int IdAccionField;

        private int IdRolField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPermisoPerfil
        {
            get
            {
                return this.IdPermisoPerfilField;
            }
            set
            {
                this.IdPermisoPerfilField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Aplicacion Aplicacion
        {
            get
            {
                return this.AplicacionField;
            }
            set
            {
                this.AplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Modulo Modulo
        {
            get
            {
                return this.ModuloField;
            }
            set
            {
                this.ModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Pagina Pagina
        {
            get
            {
                return this.PaginaField;
            }
            set
            {
                this.PaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Accion Accion
        {
            get
            {
                return this.AccionField;
            }
            set
            {
                this.AccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Rol Rol
        {
            get
            {
                return this.RolField;
            }
            set
            {
                this.RolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public int IdPagina
        {
            get
            {
                return this.IdPaginaField;
            }
            set
            {
                this.IdPaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public int IdAccion
        {
            get
            {
                return this.IdAccionField;
            }
            set
            {
                this.IdAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Modulo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Modulo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdModuloField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Aplicacion AplicacionField;

        private string NombreField;

        private string DescripcionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.ListaModuloTraductor ListaModuloTraductorField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Aplicacion Aplicacion
        {
            get
            {
                return this.AplicacionField;
            }
            set
            {
                this.AplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioPerfil.ListaModuloTraductor ListaModuloTraductor
        {
            get
            {
                return this.ListaModuloTraductorField;
            }
            set
            {
                this.ListaModuloTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Pagina", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Pagina : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdPaginaField;

        private int IdPaginaPadreField;

        private string UrlField;

        private string NombreField;

        private string IconoField;

        private int NivelField;

        private int OrdenField;

        private bool VisibleField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Modulo ModuloField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Grupo GrupoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        private int IdAgrupacionField;

        private int IdTamanoMenuField;

        private string DescripcionAgrupacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPagina
        {
            get
            {
                return this.IdPaginaField;
            }
            set
            {
                this.IdPaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPaginaPadre
        {
            get
            {
                return this.IdPaginaPadreField;
            }
            set
            {
                this.IdPaginaPadreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Icono
        {
            get
            {
                return this.IconoField;
            }
            set
            {
                this.IconoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public int Nivel
        {
            get
            {
                return this.NivelField;
            }
            set
            {
                this.NivelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public int Orden
        {
            get
            {
                return this.OrdenField;
            }
            set
            {
                this.OrdenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public bool Visible
        {
            get
            {
                return this.VisibleField;
            }
            set
            {
                this.VisibleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Modulo Modulo
        {
            get
            {
                return this.ModuloField;
            }
            set
            {
                this.ModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Grupo Grupo
        {
            get
            {
                return this.GrupoField;
            }
            set
            {
                this.GrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public int IdAgrupacion
        {
            get
            {
                return this.IdAgrupacionField;
            }
            set
            {
                this.IdAgrupacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public int IdTamanoMenu
        {
            get
            {
                return this.IdTamanoMenuField;
            }
            set
            {
                this.IdTamanoMenuField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public string DescripcionAgrupacion
        {
            get
            {
                return this.DescripcionAgrupacionField;
            }
            set
            {
                this.DescripcionAgrupacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Accion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Accion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAccionField;

        private string CodigoHTMLField;

        private string NombreField;

        private string EtiquetaField;

        private string MensajeToolTipField;

        private string EventoField;

        private bool ActivoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Grupo GrupoField;

        private int TamañoMenuField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccion
        {
            get
            {
                return this.IdAccionField;
            }
            set
            {
                this.IdAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string CodigoHTML
        {
            get
            {
                return this.CodigoHTMLField;
            }
            set
            {
                this.CodigoHTMLField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Etiqueta
        {
            get
            {
                return this.EtiquetaField;
            }
            set
            {
                this.EtiquetaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string MensajeToolTip
        {
            get
            {
                return this.MensajeToolTipField;
            }
            set
            {
                this.MensajeToolTipField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Grupo Grupo
        {
            get
            {
                return this.GrupoField;
            }
            set
            {
                this.GrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public int TamañoMenu
        {
            get
            {
                return this.TamañoMenuField;
            }
            set
            {
                this.TamañoMenuField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaModuloTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "ModuloTraductor")]
    public class ListaModuloTraductor : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.ModuloTraductor>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuloTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class ModuloTraductor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdModuloTraductorField;

        private int IdLenguajeField;

        private int IdModuloField;

        private string NombreField;

        private bool ActivoField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Lenguaje LenguajeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModuloTraductor
        {
            get
            {
                return this.IdModuloTraductorField;
            }
            set
            {
                this.IdModuloTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Lenguaje Lenguaje
        {
            get
            {
                return this.LenguajeField;
            }
            set
            {
                this.LenguajeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Grupo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Grupo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdGrupoField;

        private string CodigoField;

        private string NombreField;

        private string AbreviaturaField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Estado EstadoField;

        private string IdsGrupoField;

        private bool CheckField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrupo
        {
            get
            {
                return this.IdGrupoField;
            }
            set
            {
                this.IdGrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Abreviatura
        {
            get
            {
                return this.AbreviaturaField;
            }
            set
            {
                this.AbreviaturaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string IdsGrupo
        {
            get
            {
                return this.IdsGrupoField;
            }
            set
            {
                this.IdsGrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPagina", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Pagina")]
    public class ListaPagina : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.Pagina>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPaginaAccion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "PaginaAccion")]
    public class ListaPaginaAccion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioPerfil.PaginaAccion>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaginaAccion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class PaginaAccion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdPaginaAccionField;

        private bool ChkAgregarField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Accion AccionField;

        private Komatsu.Core.Seguridad.ServicioPerfil.Pagina PaginaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPaginaAccion
        {
            get
            {
                return this.IdPaginaAccionField;
            }
            set
            {
                this.IdPaginaAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public bool ChkAgregar
        {
            get
            {
                return this.ChkAgregarField;
            }
            set
            {
                this.ChkAgregarField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Accion Accion
        {
            get
            {
                return this.AccionField;
            }
            set
            {
                this.AccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioPerfil.Pagina Pagina
        {
            get
            {
                return this.PaginaField;
            }
            set
            {
                this.PaginaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Komatsu.Core.Seguridad.ServicioPerfil.IServicioPerfil")]
    public interface IServicioPerfil
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/CrearPerfil", ReplyAction = "http://tempuri.org/IServicioPerfil/CrearPerfilResponse")]
        Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion CrearPerfil(Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion oPerfilTransaccion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/CrearPerfil", ReplyAction = "http://tempuri.org/IServicioPerfil/CrearPerfilResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion> CrearPerfilAsync(Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion oPerfilTransaccion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ListarTreeview", ReplyAction = "http://tempuri.org/IServicioPerfil/ListarTreeviewResponse")]
        Komatsu.Core.Seguridad.ServicioPerfil.ListaTreeviewHierarchyObject ListarTreeview(int IdRol, int IdEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ListarTreeview", ReplyAction = "http://tempuri.org/IServicioPerfil/ListarTreeviewResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaTreeviewHierarchyObject> ListarTreeviewAsync(int IdRol, int IdEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/AsignarPerfil", ReplyAction = "http://tempuri.org/IServicioPerfil/AsignarPerfilResponse")]
        int AsignarPerfil(Komatsu.Core.Seguridad.ServicioPerfil.ListaPermisoPerfil oListaPermisoPerfil);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/AsignarPerfil", ReplyAction = "http://tempuri.org/IServicioPerfil/AsignarPerfilResponse")]
        System.Threading.Tasks.Task<int> AsignarPerfilAsync(Komatsu.Core.Seguridad.ServicioPerfil.ListaPermisoPerfil oListaPermisoPerfil);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ObtenerSitemapPorUsuario", ReplyAction = "http://tempuri.org/IServicioPerfil/ObtenerSitemapPorUsuarioResponse")]
        Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina ObtenerSitemapPorUsuario(string nombreUsuario, int IdAplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ObtenerSitemapPorUsuario", ReplyAction = "http://tempuri.org/IServicioPerfil/ObtenerSitemapPorUsuarioResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina> ObtenerSitemapPorUsuarioAsync(string nombreUsuario, int IdAplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ObtenerSitemapPorUsuarioFarmacia", ReplyAction = "http://tempuri.org/IServicioPerfil/ObtenerSitemapPorUsuarioFarmaciaResponse")]
        Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina ObtenerSitemapPorUsuarioFarmacia(string nombreUsuario, int IdAplicacion, string IP);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ObtenerSitemapPorUsuarioFarmacia", ReplyAction = "http://tempuri.org/IServicioPerfil/ObtenerSitemapPorUsuarioFarmaciaResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina> ObtenerSitemapPorUsuarioFarmaciaAsync(string nombreUsuario, int IdAplicacion, string IP);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ObtenerPermisoPerfilPorGrupo", ReplyAction = "http://tempuri.org/IServicioPerfil/ObtenerPermisoPerfilPorGrupoResponse")]
        Komatsu.Core.Seguridad.ServicioPerfil.ListaPaginaAccion ObtenerPermisoPerfilPorGrupo(int IdUsuario, string IdsGrupo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuSSCAServicioPerfi" +
            "l/ObtenerPermisoPerfilPorGrupo", ReplyAction = "http://tempuri.org/IServicioPerfil/ObtenerPermisoPerfilPorGrupoResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaPaginaAccion> ObtenerPermisoPerfilPorGrupoAsync(int IdUsuario, string IdsGrupo);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPerfilChannel : Komatsu.Core.Seguridad.ServicioPerfil.IServicioPerfil, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPerfilClient : System.ServiceModel.ClientBase<Komatsu.Core.Seguridad.ServicioPerfil.IServicioPerfil>, Komatsu.Core.Seguridad.ServicioPerfil.IServicioPerfil
    {

        public ServicioPerfilClient()
        {
        }

        public ServicioPerfilClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServicioPerfilClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioPerfilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioPerfilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion CrearPerfil(Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion oPerfilTransaccion)
        {
            return base.Channel.CrearPerfil(oPerfilTransaccion);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion> CrearPerfilAsync(Komatsu.Core.Seguridad.ServicioPerfil.PerfilTransaccion oPerfilTransaccion)
        {
            return base.Channel.CrearPerfilAsync(oPerfilTransaccion);
        }

        public Komatsu.Core.Seguridad.ServicioPerfil.ListaTreeviewHierarchyObject ListarTreeview(int IdRol, int IdEmpresa)
        {
            return base.Channel.ListarTreeview(IdRol, IdEmpresa);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaTreeviewHierarchyObject> ListarTreeviewAsync(int IdRol, int IdEmpresa)
        {
            return base.Channel.ListarTreeviewAsync(IdRol, IdEmpresa);
        }

        public int AsignarPerfil(Komatsu.Core.Seguridad.ServicioPerfil.ListaPermisoPerfil oListaPermisoPerfil)
        {
            return base.Channel.AsignarPerfil(oListaPermisoPerfil);
        }

        public System.Threading.Tasks.Task<int> AsignarPerfilAsync(Komatsu.Core.Seguridad.ServicioPerfil.ListaPermisoPerfil oListaPermisoPerfil)
        {
            return base.Channel.AsignarPerfilAsync(oListaPermisoPerfil);
        }

        public Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina ObtenerSitemapPorUsuario(string nombreUsuario, int IdAplicacion)
        {
            return base.Channel.ObtenerSitemapPorUsuario(nombreUsuario, IdAplicacion);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina> ObtenerSitemapPorUsuarioAsync(string nombreUsuario, int IdAplicacion)
        {
            return base.Channel.ObtenerSitemapPorUsuarioAsync(nombreUsuario, IdAplicacion);
        }

        public Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina ObtenerSitemapPorUsuarioFarmacia(string nombreUsuario, int IdAplicacion, string IP)
        {
            return base.Channel.ObtenerSitemapPorUsuarioFarmacia(nombreUsuario, IdAplicacion, IP);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaPagina> ObtenerSitemapPorUsuarioFarmaciaAsync(string nombreUsuario, int IdAplicacion, string IP)
        {
            return base.Channel.ObtenerSitemapPorUsuarioFarmaciaAsync(nombreUsuario, IdAplicacion, IP);
        }

        public Komatsu.Core.Seguridad.ServicioPerfil.ListaPaginaAccion ObtenerPermisoPerfilPorGrupo(int IdUsuario, string IdsGrupo)
        {
            return base.Channel.ObtenerPermisoPerfilPorGrupo(IdUsuario, IdsGrupo);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioPerfil.ListaPaginaAccion> ObtenerPermisoPerfilPorGrupoAsync(int IdUsuario, string IdsGrupo)
        {
            return base.Channel.ObtenerPermisoPerfilPorGrupoAsync(IdUsuario, IdsGrupo);
        }
    }
}
