//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.ServicioRol
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Rol", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdRolField;

        private bool SiSuperAdmiField;

        private string NombreField;

        private Komatsu.Core.Seguridad.ServicioRol.Estado EstadoField;

        private bool SiRangoField;

        private System.DateTime FechaInicioField;

        private System.DateTime FechaFinField;

        private Komatsu.Core.Seguridad.ServicioRol.Aplicacion AplicacionField;

        private Komatsu.Core.Seguridad.ServicioRol.Usuario UsuarioField;

        private int IdCentroAtencionField;

        private Komatsu.Core.Seguridad.ServicioRol.ListaOperacion ListaOperacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiSuperAdmi
        {
            get
            {
                return this.SiSuperAdmiField;
            }
            set
            {
                this.SiSuperAdmiField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioRol.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool SiRango
        {
            get
            {
                return this.SiRangoField;
            }
            set
            {
                this.SiRangoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public System.DateTime FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public Komatsu.Core.Seguridad.ServicioRol.Aplicacion Aplicacion
        {
            get
            {
                return this.AplicacionField;
            }
            set
            {
                this.AplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public Komatsu.Core.Seguridad.ServicioRol.Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public int IdCentroAtencion
        {
            get
            {
                return this.IdCentroAtencionField;
            }
            set
            {
                this.IdCentroAtencionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public Komatsu.Core.Seguridad.ServicioRol.ListaOperacion ListaOperacion
        {
            get
            {
                return this.ListaOperacionField;
            }
            set
            {
                this.ListaOperacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Estado", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdEstadoField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Aplicacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Aplicacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAplicacionField;

        private string NombreField;

        private string DescripcionField;

        private string UrlField;

        private Komatsu.Core.Seguridad.ServicioRol.ListaAplicacionTraductor ListaAplicacionTraductorField;

        private Komatsu.Core.Seguridad.ServicioRol.Empresa EmpresaField;

        private Komatsu.Core.Seguridad.ServicioRol.Estado EstadoField;

        private bool CheckField;

        private string IdsAplicacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioRol.ListaAplicacionTraductor ListaAplicacionTraductor
        {
            get
            {
                return this.ListaAplicacionTraductorField;
            }
            set
            {
                this.ListaAplicacionTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioRol.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public Komatsu.Core.Seguridad.ServicioRol.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string IdsAplicacion
        {
            get
            {
                return this.IdsAplicacionField;
            }
            set
            {
                this.IdsAplicacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Usuario", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdUsuarioField;

        private string CodigoEmpField;

        private string EmailCoorporativoField;

        private string NombreApellidoField;

        private Komatsu.Core.Seguridad.ServicioRol.Estado EstadoField;

        private string UserNameField;

        private Komatsu.Core.Seguridad.ServicioRol.UsuarioTipo UsuarioTipoField;

        private Komatsu.Core.Seguridad.ServicioRol.ListaRol ListaRolField;

        private string ContentStyleField;

        private string SexoField;

        private string CorreoField;

        private string CorreoBoletaField;

        private string DireccionField;

        private System.DateTime FechaNacimientoField;

        private Komatsu.Core.Seguridad.ServicioRol.Empresa EmpresaField;

        private string DNIField;

        private int IdSociedadField;

        private string SociedadDescripcionCortaField;

        private int IdAreaBUField;

        private string AreaBUDescripcionCortaField;

        private int IdCargoField;

        private string CargoDescripcionCortaField;

        private int IdAplicacionField;

        private int IdComiteField;

        private int ActivoField;

        private string PasswordField;

        private Komatsu.Core.Seguridad.ServicioRol.Cargo CargoField;

        private Komatsu.Core.Seguridad.ServicioRol.Area AreaField;

        private string IdAreasField;

        private bool CambiarPasswordField;

        private Komatsu.Core.Seguridad.ServicioRol.Empresa EmpresaRelacionadaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string CodigoEmp
        {
            get
            {
                return this.CodigoEmpField;
            }
            set
            {
                this.CodigoEmpField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string EmailCoorporativo
        {
            get
            {
                return this.EmailCoorporativoField;
            }
            set
            {
                this.EmailCoorporativoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string NombreApellido
        {
            get
            {
                return this.NombreApellidoField;
            }
            set
            {
                this.NombreApellidoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioRol.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public Komatsu.Core.Seguridad.ServicioRol.UsuarioTipo UsuarioTipo
        {
            get
            {
                return this.UsuarioTipoField;
            }
            set
            {
                this.UsuarioTipoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public Komatsu.Core.Seguridad.ServicioRol.ListaRol ListaRol
        {
            get
            {
                return this.ListaRolField;
            }
            set
            {
                this.ListaRolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string ContentStyle
        {
            get
            {
                return this.ContentStyleField;
            }
            set
            {
                this.ContentStyleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public string CorreoBoleta
        {
            get
            {
                return this.CorreoBoletaField;
            }
            set
            {
                this.CorreoBoletaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 14)]
        public Komatsu.Core.Seguridad.ServicioRol.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 15)]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 16)]
        public int IdSociedad
        {
            get
            {
                return this.IdSociedadField;
            }
            set
            {
                this.IdSociedadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 17)]
        public string SociedadDescripcionCorta
        {
            get
            {
                return this.SociedadDescripcionCortaField;
            }
            set
            {
                this.SociedadDescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 18)]
        public int IdAreaBU
        {
            get
            {
                return this.IdAreaBUField;
            }
            set
            {
                this.IdAreaBUField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 19)]
        public string AreaBUDescripcionCorta
        {
            get
            {
                return this.AreaBUDescripcionCortaField;
            }
            set
            {
                this.AreaBUDescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 20)]
        public int IdCargo
        {
            get
            {
                return this.IdCargoField;
            }
            set
            {
                this.IdCargoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 21)]
        public string CargoDescripcionCorta
        {
            get
            {
                return this.CargoDescripcionCortaField;
            }
            set
            {
                this.CargoDescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 22)]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 23)]
        public int IdComite
        {
            get
            {
                return this.IdComiteField;
            }
            set
            {
                this.IdComiteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 24)]
        public int Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 25)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 26)]
        public Komatsu.Core.Seguridad.ServicioRol.Cargo Cargo
        {
            get
            {
                return this.CargoField;
            }
            set
            {
                this.CargoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 27)]
        public Komatsu.Core.Seguridad.ServicioRol.Area Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 28)]
        public string IdAreas
        {
            get
            {
                return this.IdAreasField;
            }
            set
            {
                this.IdAreasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 29)]
        public bool CambiarPassword
        {
            get
            {
                return this.CambiarPasswordField;
            }
            set
            {
                this.CambiarPasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 30)]
        public Komatsu.Core.Seguridad.ServicioRol.Empresa EmpresaRelacionada
        {
            get
            {
                return this.EmpresaRelacionadaField;
            }
            set
            {
                this.EmpresaRelacionadaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaOperacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Operacion")]
    public class ListaOperacion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioRol.Operacion>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empresa", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdEmpresaField;

        private string NombreField;

        private string AbreviaturaField;

        private Komatsu.Core.Seguridad.ServicioRol.Estado EstadoField;

        private bool CheckField;

        private string IdsEmpresaField;

        private string CodigoEmpresaField;

        private string ContentStyleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Abreviatura
        {
            get
            {
                return this.AbreviaturaField;
            }
            set
            {
                this.AbreviaturaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioRol.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string IdsEmpresa
        {
            get
            {
                return this.IdsEmpresaField;
            }
            set
            {
                this.IdsEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public string CodigoEmpresa
        {
            get
            {
                return this.CodigoEmpresaField;
            }
            set
            {
                this.CodigoEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string ContentStyle
        {
            get
            {
                return this.ContentStyleField;
            }
            set
            {
                this.ContentStyleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaAplicacionTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "AplicacionTraductor")]
    public class ListaAplicacionTraductor : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioRol.AplicacionTraductor>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AplicacionTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class AplicacionTraductor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAplicacionTraductorField;

        private int IdLenguajeField;

        private int IdAplicacionField;

        private string NombreField;

        private Komatsu.Core.Seguridad.ServicioRol.Lenguaje LenguajeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAplicacionTraductor
        {
            get
            {
                return this.IdAplicacionTraductorField;
            }
            set
            {
                this.IdAplicacionTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioRol.Lenguaje Lenguaje
        {
            get
            {
                return this.LenguajeField;
            }
            set
            {
                this.LenguajeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Lenguaje", Namespace = "http://Komatsu.SSCA.Seguridad.Model/2013/DCKomatsuSeguridad")]
    public partial class Lenguaje : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdLenguajeField;

        private string NombreField;

        private string DiminutivoField;

        private bool ActivoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Diminutivo
        {
            get
            {
                return this.DiminutivoField;
            }
            set
            {
                this.DiminutivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UsuarioTipo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class UsuarioTipo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdUsuarioTipoField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioTipo
        {
            get
            {
                return this.IdUsuarioTipoField;
            }
            set
            {
                this.IdUsuarioTipoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Cargo", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts.Gene" +
        "ratedCode")]
    public partial class Cargo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescripcionField;

        private int EstadoField;

        private int IdCargoField;

        private string NombreCargoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCargo
        {
            get
            {
                return this.IdCargoField;
            }
            set
            {
                this.IdCargoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCargo
        {
            get
            {
                return this.NombreCargoField;
            }
            set
            {
                this.NombreCargoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Area", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts")]
    public partial class Area : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CorrelativoField;

        private string DescripcionField;

        private int EstadoField;

        private int IdAreaField;

        private bool IsCheckedField;

        private bool IsEnableCheckField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correlativo
        {
            get
            {
                return this.CorrelativoField;
            }
            set
            {
                this.CorrelativoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea
        {
            get
            {
                return this.IdAreaField;
            }
            set
            {
                this.IdAreaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChecked
        {
            get
            {
                return this.IsCheckedField;
            }
            set
            {
                this.IsCheckedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnableCheck
        {
            get
            {
                return this.IsEnableCheckField;
            }
            set
            {
                this.IsEnableCheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaRol", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Rol")]
    public class ListaRol : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioRol.Rol>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Operacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Operacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdOperacionField;

        private string DescripcionField;

        private Komatsu.Core.Seguridad.ServicioRol.Estado EstadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOperacion
        {
            get
            {
                return this.IdOperacionField;
            }
            set
            {
                this.IdOperacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public Komatsu.Core.Seguridad.ServicioRol.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Paginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int PageField;

        private int RowsPerPageField;

        private int RowCountField;

        private string SortTypeField;

        private string SortDirField;

        private string FooterDescField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string FooterDesc
        {
            get
            {
                return this.FooterDescField;
            }
            set
            {
                this.FooterDescField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RolPaginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class RolPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioRol.Paginacion PaginacionField;

        private Komatsu.Core.Seguridad.ServicioRol.ListaRol ListaRolField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioRol.Paginacion Paginacion
        {
            get
            {
                return this.PaginacionField;
            }
            set
            {
                this.PaginacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioRol.ListaRol ListaRol
        {
            get
            {
                return this.ListaRolField;
            }
            set
            {
                this.ListaRolField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaAplicacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Aplicacion")]
    public class ListaAplicacion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioRol.Aplicacion>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Komatsu.Core.Seguridad.ServicioRol.IServicioRol")]
    public interface IServicioRol
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarRolPaginacion", ReplyAction = "http://tempuri.org/IServicioRol/ListarRolPaginacionResponse")]
        Komatsu.Core.Seguridad.ServicioRol.RolPaginacion ListarRolPaginacion(Komatsu.Core.Seguridad.ServicioRol.Rol rol, Komatsu.Core.Seguridad.ServicioRol.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarRolPaginacion", ReplyAction = "http://tempuri.org/IServicioRol/ListarRolPaginacionResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.RolPaginacion> ListarRolPaginacionAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol, Komatsu.Core.Seguridad.ServicioRol.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarRol", ReplyAction = "http://tempuri.org/IServicioRol/ListarRolResponse")]
        Komatsu.Core.Seguridad.ServicioRol.ListaRol ListarRol();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarRol", ReplyAction = "http://tempuri.org/IServicioRol/ListarRolResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaRol> ListarRolAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/B" +
            "uscar_Rol", ReplyAction = "http://tempuri.org/IServicioRol/Buscar_RolResponse")]
        Komatsu.Core.Seguridad.ServicioRol.Rol Buscar_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/B" +
            "uscar_Rol", ReplyAction = "http://tempuri.org/IServicioRol/Buscar_RolResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.Rol> Buscar_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/I" +
            "nsertar_Rol", ReplyAction = "http://tempuri.org/IServicioRol/Insertar_RolResponse")]
        int Insertar_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/I" +
            "nsertar_Rol", ReplyAction = "http://tempuri.org/IServicioRol/Insertar_RolResponse")]
        System.Threading.Tasks.Task<int> Insertar_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/A" +
            "ctualizar_Rol", ReplyAction = "http://tempuri.org/IServicioRol/Actualizar_RolResponse")]
        int Actualizar_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/A" +
            "ctualizar_Rol", ReplyAction = "http://tempuri.org/IServicioRol/Actualizar_RolResponse")]
        System.Threading.Tasks.Task<int> Actualizar_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/A" +
            "ctualizarEstado_Rol", ReplyAction = "http://tempuri.org/IServicioRol/ActualizarEstado_RolResponse")]
        int ActualizarEstado_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/A" +
            "ctualizarEstado_Rol", ReplyAction = "http://tempuri.org/IServicioRol/ActualizarEstado_RolResponse")]
        System.Threading.Tasks.Task<int> ActualizarEstado_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/R" +
            "olesPorAplicacion", ReplyAction = "http://tempuri.org/IServicioRol/RolesPorAplicacionResponse")]
        Komatsu.Core.Seguridad.ServicioRol.ListaRol RolesPorAplicacion(Komatsu.Core.Seguridad.ServicioRol.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/R" +
            "olesPorAplicacion", ReplyAction = "http://tempuri.org/IServicioRol/RolesPorAplicacionResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaRol> RolesPorAplicacionAsync(Komatsu.Core.Seguridad.ServicioRol.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/B" +
            "uscarRolesPorUsuario", ReplyAction = "http://tempuri.org/IServicioRol/BuscarRolesPorUsuarioResponse")]
        Komatsu.Core.Seguridad.ServicioRol.ListaRol BuscarRolesPorUsuario(Komatsu.Core.Seguridad.ServicioRol.Usuario usuario);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/B" +
            "uscarRolesPorUsuario", ReplyAction = "http://tempuri.org/IServicioRol/BuscarRolesPorUsuarioResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaRol> BuscarRolesPorUsuarioAsync(Komatsu.Core.Seguridad.ServicioRol.Usuario usuario);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarAplicacion", ReplyAction = "http://tempuri.org/IServicioRol/ListarAplicacionResponse")]
        Komatsu.Core.Seguridad.ServicioRol.ListaAplicacion ListarAplicacion();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarAplicacion", ReplyAction = "http://tempuri.org/IServicioRol/ListarAplicacionResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaAplicacion> ListarAplicacionAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarOperacion", ReplyAction = "http://tempuri.org/IServicioRol/ListarOperacionResponse")]
        Komatsu.Core.Seguridad.ServicioRol.ListaOperacion ListarOperacion();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarOperacion", ReplyAction = "http://tempuri.org/IServicioRol/ListarOperacionResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaOperacion> ListarOperacionAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarOperacionesPorRol", ReplyAction = "http://tempuri.org/IServicioRol/ListarOperacionesPorRolResponse")]
        Komatsu.Core.Seguridad.ServicioRol.ListaOperacion ListarOperacionesPorRol(int idRol);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreServicioRol/L" +
            "istarOperacionesPorRol", ReplyAction = "http://tempuri.org/IServicioRol/ListarOperacionesPorRolResponse")]
        System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaOperacion> ListarOperacionesPorRolAsync(int idRol);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRolChannel : Komatsu.Core.Seguridad.ServicioRol.IServicioRol, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRolClient : System.ServiceModel.ClientBase<Komatsu.Core.Seguridad.ServicioRol.IServicioRol>, Komatsu.Core.Seguridad.ServicioRol.IServicioRol
    {

        public ServicioRolClient()
        {
        }

        public ServicioRolClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServicioRolClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioRolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioRolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Komatsu.Core.Seguridad.ServicioRol.RolPaginacion ListarRolPaginacion(Komatsu.Core.Seguridad.ServicioRol.Rol rol, Komatsu.Core.Seguridad.ServicioRol.Paginacion paginacion)
        {
            return base.Channel.ListarRolPaginacion(rol, paginacion);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.RolPaginacion> ListarRolPaginacionAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol, Komatsu.Core.Seguridad.ServicioRol.Paginacion paginacion)
        {
            return base.Channel.ListarRolPaginacionAsync(rol, paginacion);
        }

        public Komatsu.Core.Seguridad.ServicioRol.ListaRol ListarRol()
        {
            return base.Channel.ListarRol();
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaRol> ListarRolAsync()
        {
            return base.Channel.ListarRolAsync();
        }

        public Komatsu.Core.Seguridad.ServicioRol.Rol Buscar_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.Buscar_Rol(rol);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.Rol> Buscar_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.Buscar_RolAsync(rol);
        }

        public int Insertar_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.Insertar_Rol(rol);
        }

        public System.Threading.Tasks.Task<int> Insertar_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.Insertar_RolAsync(rol);
        }

        public int Actualizar_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.Actualizar_Rol(rol);
        }

        public System.Threading.Tasks.Task<int> Actualizar_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.Actualizar_RolAsync(rol);
        }

        public int ActualizarEstado_Rol(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.ActualizarEstado_Rol(rol);
        }

        public System.Threading.Tasks.Task<int> ActualizarEstado_RolAsync(Komatsu.Core.Seguridad.ServicioRol.Rol rol)
        {
            return base.Channel.ActualizarEstado_RolAsync(rol);
        }

        public Komatsu.Core.Seguridad.ServicioRol.ListaRol RolesPorAplicacion(Komatsu.Core.Seguridad.ServicioRol.Aplicacion aplicacion)
        {
            return base.Channel.RolesPorAplicacion(aplicacion);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaRol> RolesPorAplicacionAsync(Komatsu.Core.Seguridad.ServicioRol.Aplicacion aplicacion)
        {
            return base.Channel.RolesPorAplicacionAsync(aplicacion);
        }

        public Komatsu.Core.Seguridad.ServicioRol.ListaRol BuscarRolesPorUsuario(Komatsu.Core.Seguridad.ServicioRol.Usuario usuario)
        {
            return base.Channel.BuscarRolesPorUsuario(usuario);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaRol> BuscarRolesPorUsuarioAsync(Komatsu.Core.Seguridad.ServicioRol.Usuario usuario)
        {
            return base.Channel.BuscarRolesPorUsuarioAsync(usuario);
        }

        public Komatsu.Core.Seguridad.ServicioRol.ListaAplicacion ListarAplicacion()
        {
            return base.Channel.ListarAplicacion();
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaAplicacion> ListarAplicacionAsync()
        {
            return base.Channel.ListarAplicacionAsync();
        }

        public Komatsu.Core.Seguridad.ServicioRol.ListaOperacion ListarOperacion()
        {
            return base.Channel.ListarOperacion();
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaOperacion> ListarOperacionAsync()
        {
            return base.Channel.ListarOperacionAsync();
        }

        public Komatsu.Core.Seguridad.ServicioRol.ListaOperacion ListarOperacionesPorRol(int idRol)
        {
            return base.Channel.ListarOperacionesPorRol(idRol);
        }

        public System.Threading.Tasks.Task<Komatsu.Core.Seguridad.ServicioRol.ListaOperacion> ListarOperacionesPorRolAsync(int idRol)
        {
            return base.Channel.ListarOperacionesPorRolAsync(idRol);
        }
    }
}
