//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.Validation.Validation {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komatsu.Core.Seguridad.Validation.Validation.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo requerido.
        /// </summary>
        internal static string CampoRequerido {
            get {
                return ResourceManager.GetString("CampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo {0} requerido.
        /// </summary>
        internal static string CampoRequeridoCustom {
            get {
                return ResourceManager.GetString("CampoRequeridoCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos son obligatorios.
        /// </summary>
        internal static string CampoRequeridoDescripcion {
            get {
                return ResourceManager.GetString("CampoRequeridoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave ingresada no coincide con la actual.
        /// </summary>
        internal static string ClaveIngresadaNoCoincide {
            get {
                return ResourceManager.GetString("ClaveIngresadaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha ingresada no debe ser menor a la fecha actual.
        /// </summary>
        internal static string FechaNoMenorFechaActual {
            get {
                return ResourceManager.GetString("FechaNoMenorFechaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de fin no debe ser menor a la fecha de inicio.
        /// </summary>
        internal static string FechaNoMenorFechaFin {
            get {
                return ResourceManager.GetString("FechaNoMenorFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato incorrecto.
        /// </summary>
        internal static string FormatoIncorrecto {
            get {
                return ResourceManager.GetString("FormatoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato incorrecto para el campo {0}.
        /// </summary>
        internal static string FormatoIncorrectoCustom {
            get {
                return ResourceManager.GetString("FormatoIncorrectoCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de correo electrónico incorrecto.
        /// </summary>
        internal static string FormatoIncorrectoEmail {
            get {
                return ResourceManager.GetString("FormatoIncorrectoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de correo electrónico incorrecto para el campo {0}.
        /// </summary>
        internal static string FormatoIncorrectoEmailCustom {
            get {
                return ResourceManager.GetString("FormatoIncorrectoEmailCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de fecha incorrecto.
        /// </summary>
        internal static string FormatoIncorrectoFecha {
            get {
                return ResourceManager.GetString("FormatoIncorrectoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de fecha incorrecto para el campo {0}.
        /// </summary>
        internal static string FormatoIncorrectoFechaCustom {
            get {
                return ResourceManager.GetString("FormatoIncorrectoFechaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de hora incorrecto.
        /// </summary>
        internal static string FormatoIncorrectoHora {
            get {
                return ResourceManager.GetString("FormatoIncorrectoHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de hora incorrecto para el campo {0}.
        /// </summary>
        internal static string FormatoIncorrectoHoraCustom {
            get {
                return ResourceManager.GetString("FormatoIncorrectoHoraCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 7 caracteres y debe tener números y/o símbolos especiales..
        /// </summary>
        internal static string FormatoIncorrectoPassword {
            get {
                return ResourceManager.GetString("FormatoIncorrectoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de dirección web incorrecto.
        /// </summary>
        internal static string FormatoIncorrectoWeb {
            get {
                return ResourceManager.GetString("FormatoIncorrectoWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de dirección web incorrecto para el campo {0}.
        /// </summary>
        internal static string FormatoIncorrectoWebCustom {
            get {
                return ResourceManager.GetString("FormatoIncorrectoWebCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo debe tener entre {2} y {1} caracteres.
        /// </summary>
        internal static string LongitudCadena {
            get {
                return ResourceManager.GetString("LongitudCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener entre {2} y {1} caracteres.
        /// </summary>
        internal static string LongitudCadenaCustom {
            get {
                return ResourceManager.GetString("LongitudCadenaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo debe tener {1} caracteres.
        /// </summary>
        internal static string LongitudExacta {
            get {
                return ResourceManager.GetString("LongitudExacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener {1} caracteres.
        /// </summary>
        internal static string LongitudExactaCustom {
            get {
                return ResourceManager.GetString("LongitudExactaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor debe estar entre {1} y {2}.
        /// </summary>
        internal static string RangoValores {
            get {
                return ResourceManager.GetString("RangoValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor para {0} debe estar entre {1} y {2}.
        /// </summary>
        internal static string RangoValoresCustom {
            get {
                return ResourceManager.GetString("RangoValoresCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un item.
        /// </summary>
        internal static string SeleccionNecesaria {
            get {
                return ResourceManager.GetString("SeleccionNecesaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un item para el campo {0}.
        /// </summary>
        internal static string SeleccionNecesariaCustom {
            get {
                return ResourceManager.GetString("SeleccionNecesariaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo sólo admite decimales.
        /// </summary>
        internal static string SoloDecimal {
            get {
                return ResourceManager.GetString("SoloDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} sólo admite decimales.
        /// </summary>
        internal static string SoloDecimalCustom {
            get {
                return ResourceManager.GetString("SoloDecimalCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo sólo admite letras.
        /// </summary>
        internal static string SoloLetras {
            get {
                return ResourceManager.GetString("SoloLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} sólo admite letras.
        /// </summary>
        internal static string SoloLetrasCustom {
            get {
                return ResourceManager.GetString("SoloLetrasCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo sólo admite letras y números.
        /// </summary>
        internal static string SoloLetrasNumeros {
            get {
                return ResourceManager.GetString("SoloLetrasNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo sólo admite letras, números y caracteres especiales.
        /// </summary>
        internal static string SoloLetrasNumerosCaracterEsp {
            get {
                return ResourceManager.GetString("SoloLetrasNumerosCaracterEsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} sólo admite letras, números y caracteres especiales.
        /// </summary>
        internal static string SoloLetrasNumerosCaracterEspCustom {
            get {
                return ResourceManager.GetString("SoloLetrasNumerosCaracterEspCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} sólo admite letras y números.
        /// </summary>
        internal static string SoloLetrasNumerosCustom {
            get {
                return ResourceManager.GetString("SoloLetrasNumerosCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo sólo admite letras, números y guiones.
        /// </summary>
        internal static string SoloLetrasNumerosGuiones {
            get {
                return ResourceManager.GetString("SoloLetrasNumerosGuiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo sólo admite números.
        /// </summary>
        internal static string SoloNumeros {
            get {
                return ResourceManager.GetString("SoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} sólo admite números.
        /// </summary>
        internal static string SoloNumerosCustom {
            get {
                return ResourceManager.GetString("SoloNumerosCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado no se encuentra registrado.
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor ingresado es incorrecto.
        /// </summary>
        internal static string ValorIncorrecto {
            get {
                return ResourceManager.GetString("ValorIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor ingresado es incorrecto para el campo {0}.
        /// </summary>
        internal static string ValorIncorrectoCustom {
            get {
                return ResourceManager.GetString("ValorIncorrectoCustom", resourceCulture);
            }
        }
    }
}
