//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.Validation.Security {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komatsu.Core.Seguridad.Validation.Security.Security", typeof(Security).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se activó correctamente.
        /// </summary>
        public static string Activar_Correcto {
            get {
                return ResourceManager.GetString("Activar_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error durante la activación.
        /// </summary>
        public static string Activar_Incorrecto {
            get {
                return ResourceManager.GetString("Activar_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizó correctamente.
        /// </summary>
        public static string Actualizacion_Correcta {
            get {
                return ResourceManager.GetString("Actualizacion_Correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error durante la actualización .
        /// </summary>
        public static string Actualizacion_Incorrecta {
            get {
                return ResourceManager.GetString("Actualizacion_Incorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación correctamente.
        /// </summary>
        public static string Asignacion_Correcta {
            get {
                return ResourceManager.GetString("Asignacion_Correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error durante la asignación .
        /// </summary>
        public static string Asignacion_Incorrecta {
            get {
                return ResourceManager.GetString("Asignacion_Incorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un registro.
        /// </summary>
        public static string Asignacion_Seleccione {
            get {
                return ResourceManager.GetString("Asignacion_Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea activar ?.
        /// </summary>
        public static string Confirmacion_Activar {
            get {
                return ResourceManager.GetString("Confirmacion_Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea actualizar el registro ?.
        /// </summary>
        public static string Confirmacion_Actualizar {
            get {
                return ResourceManager.GetString("Confirmacion_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea cancelar el registro ?.
        /// </summary>
        public static string Confirmacion_Cancelar {
            get {
                return ResourceManager.GetString("Confirmacion_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea desactivarlo ?.
        /// </summary>
        public static string Confirmacion_Desactivar {
            get {
                return ResourceManager.GetString("Confirmacion_Desactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea registrarlo ?.
        /// </summary>
        public static string Confirmacion_Registrar {
            get {
                return ResourceManager.GetString("Confirmacion_Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se desactivó correctamente.
        /// </summary>
        public static string Desactivar_Correcto {
            get {
                return ResourceManager.GetString("Desactivar_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error durante la desactivación .
        /// </summary>
        public static string Desactivar_Incorrecto {
            get {
                return ResourceManager.GetString("Desactivar_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede insertar DNI duplicado.
        /// </summary>
        public static string DNI_duplicado {
            get {
                return ResourceManager.GetString("DNI_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino correctamente.
        /// </summary>
        public static string Eliminar_Correcto {
            get {
                return ResourceManager.GetString("Eliminar_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al eliminar .
        /// </summary>
        public static string Eliminar_Incorrecto {
            get {
                return ResourceManager.GetString("Eliminar_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Estado_Activo {
            get {
                return ResourceManager.GetString("Estado_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivo.
        /// </summary>
        public static string Estado_Inactivo {
            get {
                return ResourceManager.GetString("Estado_Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Empleado Duplicado.
        /// </summary>
        public static string Nombre_duplicado {
            get {
                return ResourceManager.GetString("Nombre_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se registró correctamente.
        /// </summary>
        public static string Registro_Correcto {
            get {
                return ResourceManager.GetString("Registro_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error durante el registro .
        /// </summary>
        public static string Registro_Incorrecto {
            get {
                return ResourceManager.GetString("Registro_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro {0} ya se encuentra registrado.
        /// </summary>
        public static string Registro_Repetido {
            get {
                return ResourceManager.GetString("Registro_Repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la aplicación ya existe un rol administrador.
        /// </summary>
        public static string Rol_AdmiEnAplicacion {
            get {
                return ResourceManager.GetString("Rol_AdmiEnAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede desactivar el rol ya que es de tipo Administrador.
        /// </summary>
        public static string Rol_Desactivar_Administrador {
            get {
                return ResourceManager.GetString("Rol_Desactivar_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario Duplicado.
        /// </summary>
        public static string Usuario_duplicado {
            get {
                return ResourceManager.GetString("Usuario_duplicado", resourceCulture);
            }
        }
    }
}
