//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.Validation.Settings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komatsu.Core.Seguridad.Validation.Settings.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Files/.
        /// </summary>
        public static string FileFolderUrl {
            get {
                return ResourceManager.GetString("FileFolderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6.
        /// </summary>
        public static string FileMaxAmount {
            get {
                return ResourceManager.GetString("FileMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5120.
        /// </summary>
        public static string FileMaxSizeAllowKB {
            get {
                return ResourceManager.GetString("FileMaxSizeAllowKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.doc, *.docx, *.xls, *.xlsx, *.ppt, *.pptx, *.pps, *.ppsx, *.odf, *.ods, *.odt, *.otp, *.ots, *.ott, *.pdf, *.txt.
        /// </summary>
        public static string FileTypesAllow_Documents {
            get {
                return ResourceManager.GetString("FileTypesAllow_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        public static string FileTypesAllow_Documents_Active {
            get {
                return ResourceManager.GetString("FileTypesAllow_Documents_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.jpg, *.jpeg, *.png, *.gif, *.bmp, *.tiff.
        /// </summary>
        public static string FileTypesAllow_Images {
            get {
                return ResourceManager.GetString("FileTypesAllow_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        public static string FileTypesAllow_Images_Active {
            get {
                return ResourceManager.GetString("FileTypesAllow_Images_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.mp3, *.aac, *.wma, *.3gp, *.avi, *.wmv, *.mpeg4.
        /// </summary>
        public static string FileTypesAllow_Media {
            get {
                return ResourceManager.GetString("FileTypesAllow_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        public static string FileTypesAllow_Media_Active {
            get {
                return ResourceManager.GetString("FileTypesAllow_Media_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FileTypesAllow_Others {
            get {
                return ResourceManager.GetString("FileTypesAllow_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a False.
        /// </summary>
        public static string FileTypesAllow_Others_Active {
            get {
                return ResourceManager.GetString("FileTypesAllow_Others_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.zip, *.rar.
        /// </summary>
        public static string FileTypesAllow_Package {
            get {
                return ResourceManager.GetString("FileTypesAllow_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        public static string FileTypesAllow_Package_Active {
            get {
                return ResourceManager.GetString("FileTypesAllow_Package_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        public static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Mail/EnvioCorreo.htm.
        /// </summary>
        public static string Mail_Document_Path {
            get {
                return ResourceManager.GetString("Mail_Document_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content/images/cummins-header.png.
        /// </summary>
        public static string Mail_Image_Cummins {
            get {
                return ResourceManager.GetString("Mail_Image_Cummins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content/images/komatsu-header.png.
        /// </summary>
        public static string Mail_Image_Komatsu {
            get {
                return ResourceManager.GetString("Mail_Image_Komatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de Seguridad.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Komatsu.
        /// </summary>
        public static string SystemNameAcronym {
            get {
                return ResourceManager.GetString("SystemNameAcronym", resourceCulture);
            }
        }
    }
}
