//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.ServicioConfiguracion
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empresa", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdEmpresaField;

        private string NombreField;

        private string AbreviaturaField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Estado EstadoField;

        private bool CheckField;

        private string IdsEmpresaField;

        private string CodigoEmpresaField;

        private string ContentStyleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Abreviatura
        {
            get
            {
                return this.AbreviaturaField;
            }
            set
            {
                this.AbreviaturaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string IdsEmpresa
        {
            get
            {
                return this.IdsEmpresaField;
            }
            set
            {
                this.IdsEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public string CodigoEmpresa
        {
            get
            {
                return this.CodigoEmpresaField;
            }
            set
            {
                this.CodigoEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string ContentStyle
        {
            get
            {
                return this.ContentStyleField;
            }
            set
            {
                this.ContentStyleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Estado", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdEstadoField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Paginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int PageField;

        private int RowsPerPageField;

        private int RowCountField;

        private string SortTypeField;

        private string SortDirField;

        private string FooterDescField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string FooterDesc
        {
            get
            {
                return this.FooterDescField;
            }
            set
            {
                this.FooterDescField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EmpresaPaginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class EmpresaPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion PaginacionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaEmpresa ListaEmpresaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion Paginacion
        {
            get
            {
                return this.PaginacionField;
            }
            set
            {
                this.PaginacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaEmpresa ListaEmpresa
        {
            get
            {
                return this.ListaEmpresaField;
            }
            set
            {
                this.ListaEmpresaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaEmpresa", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Empresa")]
    public class ListaEmpresa : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Aplicacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Aplicacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAplicacionField;

        private string NombreField;

        private string DescripcionField;

        private string UrlField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacionTraductor ListaAplicacionTraductorField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa EmpresaField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Estado EstadoField;

        private bool CheckField;

        private string IdsAplicacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacionTraductor ListaAplicacionTraductor
        {
            get
            {
                return this.ListaAplicacionTraductorField;
            }
            set
            {
                this.ListaAplicacionTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string IdsAplicacion
        {
            get
            {
                return this.IdsAplicacionField;
            }
            set
            {
                this.IdsAplicacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaAplicacionTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "AplicacionTraductor")]
    public class ListaAplicacionTraductor : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.AplicacionTraductor>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AplicacionTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class AplicacionTraductor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAplicacionTraductorField;

        private int IdLenguajeField;

        private int IdAplicacionField;

        private string NombreField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Lenguaje LenguajeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAplicacionTraductor
        {
            get
            {
                return this.IdAplicacionTraductorField;
            }
            set
            {
                this.IdAplicacionTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int IdAplicacion
        {
            get
            {
                return this.IdAplicacionField;
            }
            set
            {
                this.IdAplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Lenguaje Lenguaje
        {
            get
            {
                return this.LenguajeField;
            }
            set
            {
                this.LenguajeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Lenguaje", Namespace = "http://Komatsu.SSCA.Seguridad.Model/2013/DCKomatsuSeguridad")]
    public partial class Lenguaje : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdLenguajeField;

        private string NombreField;

        private string DiminutivoField;

        private bool ActivoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Diminutivo
        {
            get
            {
                return this.DiminutivoField;
            }
            set
            {
                this.DiminutivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AplicacionPaginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class AplicacionPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion PaginacionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacion ListaAplicacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion Paginacion
        {
            get
            {
                return this.PaginacionField;
            }
            set
            {
                this.PaginacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacion ListaAplicacion
        {
            get
            {
                return this.ListaAplicacionField;
            }
            set
            {
                this.ListaAplicacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaAplicacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Aplicacion")]
    public class ListaAplicacion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Modulo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Modulo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdModuloField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion AplicacionField;

        private string NombreField;

        private string DescripcionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModuloTraductor ListaModuloTraductorField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Estado EstadoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion Aplicacion
        {
            get
            {
                return this.AplicacionField;
            }
            set
            {
                this.AplicacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModuloTraductor ListaModuloTraductor
        {
            get
            {
                return this.ListaModuloTraductorField;
            }
            set
            {
                this.ListaModuloTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaModuloTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "ModuloTraductor")]
    public class ListaModuloTraductor : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.ModuloTraductor>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuloTraductor", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class ModuloTraductor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdModuloTraductorField;

        private int IdLenguajeField;

        private int IdModuloField;

        private string NombreField;

        private bool ActivoField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Lenguaje LenguajeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModuloTraductor
        {
            get
            {
                return this.IdModuloTraductorField;
            }
            set
            {
                this.IdModuloTraductorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int IdLenguaje
        {
            get
            {
                return this.IdLenguajeField;
            }
            set
            {
                this.IdLenguajeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Lenguaje Lenguaje
        {
            get
            {
                return this.LenguajeField;
            }
            set
            {
                this.LenguajeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ModuloPaginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class ModuloPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion PaginacionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModulo ListaModuloField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion Paginacion
        {
            get
            {
                return this.PaginacionField;
            }
            set
            {
                this.PaginacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModulo ListaModulo
        {
            get
            {
                return this.ListaModuloField;
            }
            set
            {
                this.ListaModuloField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaModulo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Modulo")]
    public class ListaModulo : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaAgrupacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Agrupacion")]
    public class ListaAgrupacion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Agrupacion>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Agrupacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Agrupacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAgrupacionField;

        private int IdModuloField;

        private string DescripcionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgrupacion
        {
            get
            {
                return this.IdAgrupacionField;
            }
            set
            {
                this.IdAgrupacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Pagina", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Pagina : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdPaginaField;

        private int IdPaginaPadreField;

        private string UrlField;

        private string NombreField;

        private string IconoField;

        private int NivelField;

        private int OrdenField;

        private bool VisibleField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo ModuloField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo GrupoField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Estado EstadoField;

        private int IdAgrupacionField;

        private int IdTamanoMenuField;

        private string DescripcionAgrupacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPagina
        {
            get
            {
                return this.IdPaginaField;
            }
            set
            {
                this.IdPaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPaginaPadre
        {
            get
            {
                return this.IdPaginaPadreField;
            }
            set
            {
                this.IdPaginaPadreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Icono
        {
            get
            {
                return this.IconoField;
            }
            set
            {
                this.IconoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public int Nivel
        {
            get
            {
                return this.NivelField;
            }
            set
            {
                this.NivelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public int Orden
        {
            get
            {
                return this.OrdenField;
            }
            set
            {
                this.OrdenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public bool Visible
        {
            get
            {
                return this.VisibleField;
            }
            set
            {
                this.VisibleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo Modulo
        {
            get
            {
                return this.ModuloField;
            }
            set
            {
                this.ModuloField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo Grupo
        {
            get
            {
                return this.GrupoField;
            }
            set
            {
                this.GrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public int IdAgrupacion
        {
            get
            {
                return this.IdAgrupacionField;
            }
            set
            {
                this.IdAgrupacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public int IdTamanoMenu
        {
            get
            {
                return this.IdTamanoMenuField;
            }
            set
            {
                this.IdTamanoMenuField = value;
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public string DescripcionAgrupacion
        {
            get
            {
                return this.DescripcionAgrupacionField;
            }
            set
            {
                this.DescripcionAgrupacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Grupo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Grupo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdGrupoField;

        private string CodigoField;

        private string NombreField;

        private string AbreviaturaField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Estado EstadoField;

        private string IdsGrupoField;

        private bool CheckField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrupo
        {
            get
            {
                return this.IdGrupoField;
            }
            set
            {
                this.IdGrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Abreviatura
        {
            get
            {
                return this.AbreviaturaField;
            }
            set
            {
                this.AbreviaturaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string IdsGrupo
        {
            get
            {
                return this.IdsGrupoField;
            }
            set
            {
                this.IdsGrupoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public bool Check
        {
            get
            {
                return this.CheckField;
            }
            set
            {
                this.CheckField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaginaPaginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class PaginaPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion PaginacionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina ListaPaginaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion Paginacion
        {
            get
            {
                return this.PaginacionField;
            }
            set
            {
                this.PaginacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina ListaPagina
        {
            get
            {
                return this.ListaPaginaField;
            }
            set
            {
                this.ListaPaginaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPagina", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Pagina")]
    public class ListaPagina : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPaginaAccion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "PaginaAccion")]
    public class ListaPaginaAccion : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaAccion>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaginaAccion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class PaginaAccion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdPaginaAccionField;

        private bool ChkAgregarField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Accion AccionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina PaginaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPaginaAccion
        {
            get
            {
                return this.IdPaginaAccionField;
            }
            set
            {
                this.IdPaginaAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public bool ChkAgregar
        {
            get
            {
                return this.ChkAgregarField;
            }
            set
            {
                this.ChkAgregarField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Accion Accion
        {
            get
            {
                return this.AccionField;
            }
            set
            {
                this.AccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina Pagina
        {
            get
            {
                return this.PaginaField;
            }
            set
            {
                this.PaginaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Accion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class Accion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAccionField;

        private string CodigoHTMLField;

        private string NombreField;

        private string EtiquetaField;

        private string MensajeToolTipField;

        private string EventoField;

        private bool ActivoField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo GrupoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccion
        {
            get
            {
                return this.IdAccionField;
            }
            set
            {
                this.IdAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string CodigoHTML
        {
            get
            {
                return this.CodigoHTMLField;
            }
            set
            {
                this.CodigoHTMLField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Etiqueta
        {
            get
            {
                return this.EtiquetaField;
            }
            set
            {
                this.EtiquetaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string MensajeToolTip
        {
            get
            {
                return this.MensajeToolTipField;
            }
            set
            {
                this.MensajeToolTipField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo Grupo
        {
            get
            {
                return this.GrupoField;
            }
            set
            {
                this.GrupoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaginaAccionPaginacion", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class PaginaAccionPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion ListaPaginaAccionField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion PaginacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion ListaPaginaAccion
        {
            get
            {
                return this.ListaPaginaAccionField;
            }
            set
            {
                this.ListaPaginaAccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion Paginacion
        {
            get
            {
                return this.PaginacionField;
            }
            set
            {
                this.PaginacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaGrupo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "Grupo")]
    public class ListaGrupo : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPaginaGrupo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", ItemName = "PaginaGrupo")]
    public class ListaPaginaGrupo : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaGrupo>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaginaGrupo", Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
    public partial class PaginaGrupo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina PaginaField;

        private Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo GrupoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina Pagina
        {
            get
            {
                return this.PaginaField;
            }
            set
            {
                this.PaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Komatsu.Core.Seguridad.ServicioConfiguracion.Grupo Grupo
        {
            get
            {
                return this.GrupoField;
            }
            set
            {
                this.GrupoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaUnidadOrganica", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts", ItemName = "UnidadOrganica")]
    public class ListaUnidadOrganica : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.UnidadOrganica>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UnidadOrganica", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts")]
    public partial class UnidadOrganica : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CorrelativoField;

        private string DescripcionField;

        private int IdUnidadOrganicaField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correlativo
        {
            get
            {
                return this.CorrelativoField;
            }
            set
            {
                this.CorrelativoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUnidadOrganica
        {
            get
            {
                return this.IdUnidadOrganicaField;
            }
            set
            {
                this.IdUnidadOrganicaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaArea", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts", ItemName = "Area")]
    public class ListaArea : System.Collections.Generic.List<Komatsu.Core.Seguridad.ServicioConfiguracion.Area>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Area", Namespace = "http://schemas.datacontract.org/2004/07/Komatsu.Core.Seguridad.DataContracts")]
    public partial class Area : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CorrelativoField;

        private string DescripcionField;

        private int IdAreaField;

        private string NombreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correlativo
        {
            get
            {
                return this.CorrelativoField;
            }
            set
            {
                this.CorrelativoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea
        {
            get
            {
                return this.IdAreaField;
            }
            set
            {
                this.IdAreaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Komatsu.Core.Seguridad.ServicioConfiguracion.IServicioConfiguracion")]
    public interface IServicioConfiguracion
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarEmpresaPaginacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarEmpresaPaginacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.EmpresaPaginacion ListarEmpresaPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/BuscarEmpresa", ReplyAction = "http://tempuri.org/IServicioConfiguracion/BuscarEmpresaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa BuscarEmpresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Insertar_Empresa", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Insertar_EmpresaResponse")]
        int Insertar_Empresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Actualizar_Empresa", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Actualizar_EmpresaResponse")]
        int Actualizar_Empresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ActualizarEstado_Empresa", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ActualizarEstado_EmpresaResponse")]
        int ActualizarEstado_Empresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarEmpresa", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarEmpresaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaEmpresa ListarEmpresa();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/BuscarEmpresasPorAplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/BuscarEmpresasPorAplicacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaEmpresa BuscarEmpresasPorAplicacion(int IdAplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarAplicacionPaginacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarAplicacionPaginacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.AplicacionPaginacion ListarAplicacionPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/BuscarAplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/BuscarAplicacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion BuscarAplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Insertar_Aplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Insertar_AplicacionResponse")]
        string Insertar_Aplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Actualizar_Aplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Actualizar_AplicacionResponse")]
        int Actualizar_Aplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ActualizarEstado_Aplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ActualizarEstado_AplicacionResponse")]
        int ActualizarEstado_Aplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarAplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarAplicacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacion ListarAplicacion();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/AplicacionPorEmpresa", ReplyAction = "http://tempuri.org/IServicioConfiguracion/AplicacionPorEmpresaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacion AplicacionPorEmpresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarModuloPaginacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarModuloPaginacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ModuloPaginacion ListarModuloPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/BuscarModulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/BuscarModuloResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo BuscarModulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Insertar_Modulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Insertar_ModuloResponse")]
        int Insertar_Modulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Actualizar_Modulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Actualizar_ModuloResponse")]
        int Actualizar_Modulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ActualizarEstado_Modulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ActualizarEstado_ModuloResponse")]
        int ActualizarEstado_Modulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarModulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarModuloResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModulo ListarModulo();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ModuloPorAplicacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ModuloPorAplicacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModulo ModuloPorAplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/getListAgrupacionModulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/getListAgrupacionModuloResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAgrupacion getListAgrupacionModulo(int IdModulo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarPaginaPaginacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarPaginaPaginacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaPaginacion ListarPaginaPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/BuscarPagina", ReplyAction = "http://tempuri.org/IServicioConfiguracion/BuscarPaginaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina BuscarPagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Insertar_Pagina", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Insertar_PaginaResponse")]
        int Insertar_Pagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina, Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion listaPaginaAccion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/Actualizar_Pagina", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Actualizar_PaginaResponse")]
        int Actualizar_Pagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina, Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion listaPaginaAccion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ActualizarEstado_Pagina", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ActualizarEstado_PaginaResponse")]
        int ActualizarEstado_Pagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarPagina", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarPaginaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina ListarPagina();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/PaginaPorModulo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/PaginaPorModuloResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina PaginaPorModulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/PaginaPadreListar", ReplyAction = "http://tempuri.org/IServicioConfiguracion/PaginaPadreListarResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina PaginaPadreListar(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarAccionPaginacion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarAccionPaginacionResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaAccionPaginacion ListarAccionPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaAccion paginaAccion, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/AsignarPaginaAccion", ReplyAction = "http://tempuri.org/IServicioConfiguracion/AsignarPaginaAccionResponse")]
        int AsignarPaginaAccion(Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion listaPaginaAccion);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarGrupo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarGrupoResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaGrupo ListarGrupo();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/AsignarPaginaGrupo", ReplyAction = "http://tempuri.org/IServicioConfiguracion/AsignarPaginaGrupoResponse")]
        int AsignarPaginaGrupo(Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaGrupo listaPaginaGrupo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/PaginaGrupo_Eliminar", ReplyAction = "http://tempuri.org/IServicioConfiguracion/PaginaGrupo_EliminarResponse")]
        int PaginaGrupo_Eliminar(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/GruposPorPagina", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GruposPorPaginaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaGrupo GruposPorPagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarUnidadOrganica", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarUnidadOrganicaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaUnidadOrganica ListarUnidadOrganica();

        [System.ServiceModel.OperationContractAttribute(Action = "http://Komatsu.Core.Seguridad.Model.ServiceContract/2013/KomatsuCoreSeguridadServ" +
            "icioConfiguracion/ListarArea", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListarAreaResponse")]
        Komatsu.Core.Seguridad.ServicioConfiguracion.ListaArea ListarArea(int idunidadorganica);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConfiguracionChannel : Komatsu.Core.Seguridad.ServicioConfiguracion.IServicioConfiguracion, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConfiguracionClient : System.ServiceModel.ClientBase<Komatsu.Core.Seguridad.ServicioConfiguracion.IServicioConfiguracion>, Komatsu.Core.Seguridad.ServicioConfiguracion.IServicioConfiguracion
    {

        public ServicioConfiguracionClient()
        {
        }

        public ServicioConfiguracionClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ServicioConfiguracionClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioConfiguracionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioConfiguracionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.EmpresaPaginacion ListarEmpresaPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion)
        {
            return base.Channel.ListarEmpresaPaginacion(empresa, paginacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa BuscarEmpresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa)
        {
            return base.Channel.BuscarEmpresa(empresa);
        }

        public int Insertar_Empresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa)
        {
            return base.Channel.Insertar_Empresa(empresa);
        }

        public int Actualizar_Empresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa)
        {
            return base.Channel.Actualizar_Empresa(empresa);
        }

        public int ActualizarEstado_Empresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Empresa empresa)
        {
            return base.Channel.ActualizarEstado_Empresa(empresa);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaEmpresa ListarEmpresa()
        {
            return base.Channel.ListarEmpresa();
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaEmpresa BuscarEmpresasPorAplicacion(int IdAplicacion)
        {
            return base.Channel.BuscarEmpresasPorAplicacion(IdAplicacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.AplicacionPaginacion ListarAplicacionPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion)
        {
            return base.Channel.ListarAplicacionPaginacion(aplicacion, paginacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion BuscarAplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion)
        {
            return base.Channel.BuscarAplicacion(aplicacion);
        }

        public string Insertar_Aplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion)
        {
            return base.Channel.Insertar_Aplicacion(aplicacion);
        }

        public int Actualizar_Aplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion)
        {
            return base.Channel.Actualizar_Aplicacion(aplicacion);
        }

        public int ActualizarEstado_Aplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion)
        {
            return base.Channel.ActualizarEstado_Aplicacion(aplicacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacion ListarAplicacion()
        {
            return base.Channel.ListarAplicacion();
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAplicacion AplicacionPorEmpresa(Komatsu.Core.Seguridad.ServicioConfiguracion.Aplicacion aplicacion)
        {
            return base.Channel.AplicacionPorEmpresa(aplicacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ModuloPaginacion ListarModuloPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion)
        {
            return base.Channel.ListarModuloPaginacion(modulo, paginacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo BuscarModulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo)
        {
            return base.Channel.BuscarModulo(modulo);
        }

        public int Insertar_Modulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo)
        {
            return base.Channel.Insertar_Modulo(modulo);
        }

        public int Actualizar_Modulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo)
        {
            return base.Channel.Actualizar_Modulo(modulo);
        }

        public int ActualizarEstado_Modulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo)
        {
            return base.Channel.ActualizarEstado_Modulo(modulo);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModulo ListarModulo()
        {
            return base.Channel.ListarModulo();
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaModulo ModuloPorAplicacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Modulo modulo)
        {
            return base.Channel.ModuloPorAplicacion(modulo);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaAgrupacion getListAgrupacionModulo(int IdModulo)
        {
            return base.Channel.getListAgrupacionModulo(IdModulo);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaPaginacion ListarPaginaPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion)
        {
            return base.Channel.ListarPaginaPaginacion(pagina, paginacion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina BuscarPagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina)
        {
            return base.Channel.BuscarPagina(pagina);
        }

        public int Insertar_Pagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina, Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion listaPaginaAccion)
        {
            return base.Channel.Insertar_Pagina(pagina, listaPaginaAccion);
        }

        public int Actualizar_Pagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina, Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion listaPaginaAccion)
        {
            return base.Channel.Actualizar_Pagina(pagina, listaPaginaAccion);
        }

        public int ActualizarEstado_Pagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina)
        {
            return base.Channel.ActualizarEstado_Pagina(pagina);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina ListarPagina()
        {
            return base.Channel.ListarPagina();
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina PaginaPorModulo(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina)
        {
            return base.Channel.PaginaPorModulo(pagina);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPagina PaginaPadreListar(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina)
        {
            return base.Channel.PaginaPadreListar(pagina);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaAccionPaginacion ListarAccionPaginacion(Komatsu.Core.Seguridad.ServicioConfiguracion.PaginaAccion paginaAccion, Komatsu.Core.Seguridad.ServicioConfiguracion.Paginacion paginacion)
        {
            return base.Channel.ListarAccionPaginacion(paginaAccion, paginacion);
        }

        public int AsignarPaginaAccion(Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaAccion listaPaginaAccion)
        {
            return base.Channel.AsignarPaginaAccion(listaPaginaAccion);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaGrupo ListarGrupo()
        {
            return base.Channel.ListarGrupo();
        }

        public int AsignarPaginaGrupo(Komatsu.Core.Seguridad.ServicioConfiguracion.ListaPaginaGrupo listaPaginaGrupo)
        {
            return base.Channel.AsignarPaginaGrupo(listaPaginaGrupo);
        }

        public int PaginaGrupo_Eliminar(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina)
        {
            return base.Channel.PaginaGrupo_Eliminar(pagina);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaGrupo GruposPorPagina(Komatsu.Core.Seguridad.ServicioConfiguracion.Pagina pagina)
        {
            return base.Channel.GruposPorPagina(pagina);
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaUnidadOrganica ListarUnidadOrganica()
        {
            return base.Channel.ListarUnidadOrganica();
        }

        public Komatsu.Core.Seguridad.ServicioConfiguracion.ListaArea ListarArea(int idunidadorganica)
        {
            return base.Channel.ListarArea(idunidadorganica);
        }
    }
}
