//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.Validation.Globals {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Globals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globals() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komatsu.Core.Seguridad.Validation.Globals.Globals", typeof(Globals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string ButtonLogOff_Text {
            get {
                return ResourceManager.GetString("ButtonLogOff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string ButtonLogOn_Text {
            get {
                return ResourceManager.GetString("ButtonLogOn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt; Anterior.
        /// </summary>
        public static string ButtonPageBack_Text {
            get {
                return ResourceManager.GetString("ButtonPageBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;&lt; Primera.
        /// </summary>
        public static string ButtonPageFirst_Text {
            get {
                return ResourceManager.GetString("ButtonPageFirst_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última &gt;&gt;.
        /// </summary>
        public static string ButtonPageLast_Text {
            get {
                return ResourceManager.GetString("ButtonPageLast_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente &gt;.
        /// </summary>
        public static string ButtonPageNext_Text {
            get {
                return ResourceManager.GetString("ButtonPageNext_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string ButtonSearch_Text {
            get {
                return ResourceManager.GetString("ButtonSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        public static string ButtonUpload_Text {
            get {
                return ResourceManager.GetString("ButtonUpload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - NINGUNO -.
        /// </summary>
        public static string ComboBox_Ninguno {
            get {
                return ResourceManager.GetString("ComboBox_Ninguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - SELECCIONE -.
        /// </summary>
        public static string ComboBox_Seleccione {
            get {
                return ResourceManager.GetString("ComboBox_Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - TODOS -.
        /// </summary>
        public static string ComboBox_Todos {
            get {
                return ResourceManager.GetString("ComboBox_Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar/Desactivar.
        /// </summary>
        public static string GridHeaderActions_ActivateDeactivate {
            get {
                return ResourceManager.GetString("GridHeaderActions_ActivateDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string GridHeaderActions_Detail {
            get {
                return ResourceManager.GetString("GridHeaderActions_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        public static string GridHeaderIsAdministrator {
            get {
                return ResourceManager.GetString("GridHeaderIsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros.
        /// </summary>
        public static string GridRowsEmpty {
            get {
                return ResourceManager.GetString("GridRowsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  No se encontraron resultados de búsqueda.
        /// </summary>
        public static string GridSearchNotFound {
            get {
                return ResourceManager.GetString("GridSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string MessageLoad {
            get {
                return ResourceManager.GetString("MessageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un momento por favor....
        /// </summary>
        public static string MessageLoadAction {
            get {
                return ResourceManager.GetString("MessageLoadAction", resourceCulture);
            }
        }
    }
}
