//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komatsu.Core.Seguridad.Validation.Globals {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komatsu.Core.Seguridad.Validation.Globals.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizó correctamente.
        /// </summary>
        public static string Actualizacion_Correcta {
            get {
                return ResourceManager.GetString("Actualizacion_Correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error mientras se realizaba la actualización.
        /// </summary>
        public static string Actualizacion_Incorrecta {
            get {
                return ResourceManager.GetString("Actualizacion_Incorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea actualizar el registro ?.
        /// </summary>
        public static string Confirmacion_Actualizar {
            get {
                return ResourceManager.GetString("Confirmacion_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea cancelar el registro ?.
        /// </summary>
        public static string Confirmacion_Cancelar {
            get {
                return ResourceManager.GetString("Confirmacion_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea eliminar el registro ?.
        /// </summary>
        public static string Confirmacion_Eliminar {
            get {
                return ResourceManager.GetString("Confirmacion_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea generar el registro ?.
        /// </summary>
        public static string Confirmacion_Registrar {
            get {
                return ResourceManager.GetString("Confirmacion_Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje de Confirmación.
        /// </summary>
        public static string Confirmacion_Titulo {
            get {
                return ResourceManager.GetString("Confirmacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos De Verificación.
        /// </summary>
        public static string Datos_Verificacion {
            get {
                return ResourceManager.GetString("Datos_Verificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje de información.
        /// </summary>
        public static string Mensaje_Informacion {
            get {
                return ResourceManager.GetString("Mensaje_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cerró la sesión correctamente.
        /// </summary>
        public static string User_LogOff_Correcto {
            get {
                return ResourceManager.GetString("User_LogOff_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema durante el cierre de sesión.
        /// </summary>
        public static string User_LogOff_Incorrecto {
            get {
                return ResourceManager.GetString("User_LogOff_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión correcto.
        /// </summary>
        public static string User_LogOn_Correcto {
            get {
                return ResourceManager.GetString("User_LogOn_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o clave incorrecta.
        /// </summary>
        public static string User_LogOn_Incorrecto {
            get {
                return ResourceManager.GetString("User_LogOn_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su sesión ha finalizado por favor vuelva iniciar sesión para continuar.
        /// </summary>
        public static string User_Session_Expired {
            get {
                return ResourceManager.GetString("User_Session_Expired", resourceCulture);
            }
        }
    }
}
