//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Accion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Accion")]
	public partial class Accion 
	{
		private int idAccion;
		private string codigoHTML;
		private string nombre;
		private string etiqueta;
		private string mensajeToolTip;
		private string evento;
        private int tamañoMenu;
		private bool activo;
		private Komatsu.Core.Seguridad.DataContracts.Grupo grupo;
		
		[WcfSerialization::DataMember(Name = "IdAccion", IsRequired = false, Order = 0)]
		public int IdAccion
		{
		  get { return idAccion; }
		  set { idAccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodigoHTML", IsRequired = false, Order = 1)]
		public string CodigoHTML
		{
		  get { return codigoHTML; }
		  set { codigoHTML = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 2)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Etiqueta", IsRequired = false, Order = 3)]
		public string Etiqueta
		{
		  get { return etiqueta; }
		  set { etiqueta = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MensajeToolTip", IsRequired = false, Order = 4)]
		public string MensajeToolTip
		{
		  get { return mensajeToolTip; }
		  set { mensajeToolTip = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Evento", IsRequired = false, Order = 5)]
		public string Evento
		{
		  get { return evento; }
		  set { evento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Activo", IsRequired = false, Order = 6)]
		public bool Activo
		{
		  get { return activo; }
		  set { activo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Grupo", IsRequired = false, Order = 7)]
		public Komatsu.Core.Seguridad.DataContracts.Grupo Grupo
		{
		  get { return grupo; }
		  set { grupo = value; }
		}

        [WcfSerialization::DataMember(Name = "TamañoMenu", IsRequired = false, Order = 8)]
        public int TamañoMenu
        {
            get { return tamañoMenu; }
            set { tamañoMenu = value; }
        }
	}
}

