//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Modulo
	/// </summary>	
    [WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Agrupacion")]
	public partial class Agrupacion 
	{
        private int idAgrupacion;
		private int idModulo;
        private string descripcion;


        [WcfSerialization::DataMember(Name = "IdAgrupacion", IsRequired = false, Order = 0)]
        public int IdAgrupacion
		{
            get { return idAgrupacion; }
            set { idAgrupacion = value; }
		}

        [WcfSerialization::DataMember(Name = "IdModulo", IsRequired = false, Order = 1)]
        public int IdModulo
		{
            get { return idModulo; }
            set { idModulo = value; }
		}

        [WcfSerialization::DataMember(Name = "Descripcion", IsRequired = false, Order = 2)]
        public string Descripcion
		{
            get { return descripcion; }
            set { descripcion = value; }
		}				
				
	}
}

