//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Aplicacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Aplicacion")]
	public partial class Aplicacion 
	{
		private int idAplicacion;
		private string nombre;
		private string descripcion;
		private string url;
		private ListaAplicacionTraductor listaAplicacionTraductor;
		private Empresa empresa;
		private Estado estado;
		private bool check;
		private string idsAplicacion;
		
		[WcfSerialization::DataMember(Name = "IdAplicacion", IsRequired = false, Order = 0)]
		public int IdAplicacion
		{
		  get { return idAplicacion; }
		  set { idAplicacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Descripcion", IsRequired = false, Order = 2)]
		public string Descripcion
		{
		  get { return descripcion; }
		  set { descripcion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Url", IsRequired = false, Order = 3)]
		public string Url
		{
		  get { return url; }
		  set { url = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListaAplicacionTraductor", IsRequired = false, Order = 4)]
		public ListaAplicacionTraductor ListaAplicacionTraductor
		{
		  get { return listaAplicacionTraductor; }
		  set { listaAplicacionTraductor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Empresa", IsRequired = false, Order = 5)]
		public Empresa Empresa
		{
		  get { return empresa; }
		  set { empresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 6)]
		public Estado Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Check", IsRequired = false, Order = 7)]
		public bool Check
		{
		  get { return check; }
		  set { check = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdsAplicacion", IsRequired = false, Order = 8)]
		public string IdsAplicacion
		{
		  get { return idsAplicacion; }
		  set { idsAplicacion = value; }
		}				
	}
}

