//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - AplicacionTraductor
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "AplicacionTraductor")]
	public partial class AplicacionTraductor 
	{
		private int idAplicacionTraductor;
		private int idLenguaje;
		private int idAplicacion;
		private string nombre;
		private Komatsu.Core.Seguridad.DataContracts.Lenguaje lenguaje;
		
		[WcfSerialization::DataMember(Name = "IdAplicacionTraductor", IsRequired = false, Order = 0)]
		public int IdAplicacionTraductor
		{
		  get { return idAplicacionTraductor; }
		  set { idAplicacionTraductor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdLenguaje", IsRequired = false, Order = 1)]
		public int IdLenguaje
		{
		  get { return idLenguaje; }
		  set { idLenguaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdAplicacion", IsRequired = false, Order = 2)]
		public int IdAplicacion
		{
		  get { return idAplicacion; }
		  set { idAplicacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 3)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Lenguaje", IsRequired = false, Order = 4)]
		public Komatsu.Core.Seguridad.DataContracts.Lenguaje Lenguaje
		{
		  get { return lenguaje; }
		  set { lenguaje = value; }
		}				
	}
}

