//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Empresa
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Empresa")]
	public partial class Empresa 
	{
		private int idEmpresa;
		private string nombre;
		private string abreviatura;
		private Estado estado;
		private bool check;
		private string idsEmpresa;
		private string codigoEmpresa;
		private string contentStyle;
		
		[WcfSerialization::DataMember(Name = "IdEmpresa", IsRequired = false, Order = 0)]
		public int IdEmpresa
		{
		  get { return idEmpresa; }
		  set { idEmpresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Abreviatura", IsRequired = false, Order = 2)]
		public string Abreviatura
		{
		  get { return abreviatura; }
		  set { abreviatura = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 3)]
		public Estado Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Check", IsRequired = false, Order = 4)]
		public bool Check
		{
		  get { return check; }
		  set { check = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdsEmpresa", IsRequired = false, Order = 5)]
		public string IdsEmpresa
		{
		  get { return idsEmpresa; }
		  set { idsEmpresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodigoEmpresa", IsRequired = false, Order = 6)]
		public string CodigoEmpresa
		{
		  get { return codigoEmpresa; }
		  set { codigoEmpresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ContentStyle", IsRequired = false, Order = 7)]
		public string ContentStyle
		{
		  get { return contentStyle; }
		  set { contentStyle = value; }
		}				
	}
}

