//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - EmpresaPaginacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "EmpresaPaginacion")]
	public partial class EmpresaPaginacion 
	{
		private Paginacion paginacion;
		private ListaEmpresa listaEmpresa;
		
		[WcfSerialization::DataMember(Name = "Paginacion", IsRequired = false, Order = 0)]
		public Paginacion Paginacion
		{
		  get { return paginacion; }
		  set { paginacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListaEmpresa", IsRequired = false, Order = 1)]
		public ListaEmpresa ListaEmpresa
		{
		  get { return listaEmpresa; }
		  set { listaEmpresa = value; }
		}				
	}
}

