//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - EmpresaAplicacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "EmpresaAplicacion")]
	public partial class EmpresaAplicacion 
	{
		private int idEmpresa;
		private int idAplicacion;
		
		[WcfSerialization::DataMember(Name = "IdEmpresa", IsRequired = false, Order = 0)]
		public int IdEmpresa
		{
		  get { return idEmpresa; }
		  set { idEmpresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdAplicacion", IsRequired = false, Order = 1)]
		public int IdAplicacion
		{
		  get { return idAplicacion; }
		  set { idAplicacion = value; }
		}				
	}
}

