//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Grupo
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Grupo")]
	public partial class Grupo 
	{
		private int idGrupo;
		private string codigo;
		private string nombre;
		private string abreviatura;
		private Estado estado;
		private string idsGrupo;
		private bool check;
		
		[WcfSerialization::DataMember(Name = "IdGrupo", IsRequired = false, Order = 0)]
		public int IdGrupo
		{
		  get { return idGrupo; }
		  set { idGrupo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Codigo", IsRequired = false, Order = 1)]
		public string Codigo
		{
		  get { return codigo; }
		  set { codigo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 2)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Abreviatura", IsRequired = false, Order = 3)]
		public string Abreviatura
		{
		  get { return abreviatura; }
		  set { abreviatura = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 4)]
		public Estado Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdsGrupo", IsRequired = false, Order = 5)]
		public string IdsGrupo
		{
		  get { return idsGrupo; }
		  set { idsGrupo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Check", IsRequired = false, Order = 6)]
		public bool Check
		{
		  get { return check; }
		  set { check = value; }
		}				
	}
}

