//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Lenguaje
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://Komatsu.SSCA.Seguridad.Model/2013/DCKomatsuSeguridad", Name = "Lenguaje")]
	public partial class Lenguaje 
	{
		private int idLenguaje;
		private string nombre;
		private string diminutivo;
		private bool activo;
		
		[WcfSerialization::DataMember(Name = "IdLenguaje", IsRequired = false, Order = 0)]
		public int IdLenguaje
		{
		  get { return idLenguaje; }
		  set { idLenguaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Diminutivo", IsRequired = false, Order = 2)]
		public string Diminutivo
		{
		  get { return diminutivo; }
		  set { diminutivo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Activo", IsRequired = false, Order = 3)]
		public bool Activo
		{
		  get { return activo; }
		  set { activo = value; }
		}				
	}
}

