//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - ListaEmpresa
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad")]
	public partial class ListaEmpresa : System.Collections.Generic.List<Empresa>
	{
	}
}

