//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - ModuloPaginacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "ModuloPaginacion")]
	public partial class ModuloPaginacion 
	{
		private Paginacion paginacion;
		private ListaModulo listaModulo;
		
		[WcfSerialization::DataMember(Name = "Paginacion", IsRequired = false, Order = 0)]
		public Paginacion Paginacion
		{
		  get { return paginacion; }
		  set { paginacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListaModulo", IsRequired = false, Order = 1)]
		public ListaModulo ListaModulo
		{
		  get { return listaModulo; }
		  set { listaModulo = value; }
		}				
	}
}

