//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Modulo
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Modulo")]
	public partial class Modulo 
	{
		private int idModulo;
		private Aplicacion aplicacion;
		private string nombre;
		private string descripcion;
		private ListaModuloTraductor listaModuloTraductor;
		private Estado estado;
		
		[WcfSerialization::DataMember(Name = "IdModulo", IsRequired = false, Order = 0)]
		public int IdModulo
		{
		  get { return idModulo; }
		  set { idModulo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Aplicacion", IsRequired = false, Order = 1)]
		public Aplicacion Aplicacion
		{
		  get { return aplicacion; }
		  set { aplicacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 2)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Descripcion", IsRequired = false, Order = 3)]
		public string Descripcion
		{
		  get { return descripcion; }
		  set { descripcion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListaModuloTraductor", IsRequired = false, Order = 4)]
		public ListaModuloTraductor ListaModuloTraductor
		{
		  get { return listaModuloTraductor; }
		  set { listaModuloTraductor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 5)]
		public Estado Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
	}
}

