//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - ModuloTraductor
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "ModuloTraductor")]
	public partial class ModuloTraductor 
	{
		private int idModuloTraductor;
		private int idLenguaje;
		private int idModulo;
		private string nombre;
		private bool activo;
		private Komatsu.Core.Seguridad.DataContracts.Lenguaje lenguaje;
		
		[WcfSerialization::DataMember(Name = "IdModuloTraductor", IsRequired = false, Order = 0)]
		public int IdModuloTraductor
		{
		  get { return idModuloTraductor; }
		  set { idModuloTraductor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdLenguaje", IsRequired = false, Order = 1)]
		public int IdLenguaje
		{
		  get { return idLenguaje; }
		  set { idLenguaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdModulo", IsRequired = false, Order = 2)]
		public int IdModulo
		{
		  get { return idModulo; }
		  set { idModulo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 3)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Activo", IsRequired = false, Order = 4)]
		public bool Activo
		{
		  get { return activo; }
		  set { activo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Lenguaje", IsRequired = false, Order = 5)]
		public Komatsu.Core.Seguridad.DataContracts.Lenguaje Lenguaje
		{
		  get { return lenguaje; }
		  set { lenguaje = value; }
		}				
	}
}

