//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Paginacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Paginacion")]
	public partial class Paginacion 
	{
		private int page;
		private int rowsPerPage;
		private int rowCount;
		private string sortType;
		private string sortDir;
		private string footerDesc;
		
		[WcfSerialization::DataMember(Name = "Page", IsRequired = false, Order = 0)]
		public int Page
		{
		  get { return page; }
		  set { page = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RowsPerPage", IsRequired = false, Order = 1)]
		public int RowsPerPage
		{
		  get { return rowsPerPage; }
		  set { rowsPerPage = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RowCount", IsRequired = false, Order = 2)]
		public int RowCount
		{
		  get { return rowCount; }
		  set { rowCount = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SortType", IsRequired = false, Order = 3)]
		public string SortType
		{
		  get { return sortType; }
		  set { sortType = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SortDir", IsRequired = false, Order = 4)]
		public string SortDir
		{
		  get { return sortDir; }
		  set { sortDir = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FooterDesc", IsRequired = false, Order = 5)]
		public string FooterDesc
		{
		  get { return footerDesc; }
		  set { footerDesc = value; }
		}				
	}
}

