//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - PaginaAccion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "PaginaAccion")]
	public partial class PaginaAccion 
	{
		private int idPaginaAccion;
		private bool chkAgregar;
		private Accion accion;
		private Pagina pagina;
		
		[WcfSerialization::DataMember(Name = "IdPaginaAccion", IsRequired = false, Order = 0)]
		public int IdPaginaAccion
		{
		  get { return idPaginaAccion; }
		  set { idPaginaAccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ChkAgregar", IsRequired = false, Order = 1)]
		public bool ChkAgregar
		{
		  get { return chkAgregar; }
		  set { chkAgregar = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Accion", IsRequired = false, Order = 2)]
		public Accion Accion
		{
		  get { return accion; }
		  set { accion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Pagina", IsRequired = false, Order = 3)]
		public Pagina Pagina
		{
		  get { return pagina; }
		  set { pagina = value; }
		}				
	}
}

