//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - PaginaGrupo
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "PaginaGrupo")]
	public partial class PaginaGrupo 
	{
		private Pagina pagina;
		private Grupo grupo;
		
		[WcfSerialization::DataMember(Name = "Pagina", IsRequired = false, Order = 0)]
		public Pagina Pagina
		{
		  get { return pagina; }
		  set { pagina = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Grupo", IsRequired = false, Order = 1)]
		public Grupo Grupo
		{
		  get { return grupo; }
		  set { grupo = value; }
		}				
	}
}

