//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - PaginaAccionPaginacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "PaginaAccionPaginacion")]
	public partial class PaginaAccionPaginacion 
	{
		private ListaPaginaAccion listaPaginaAccion;
		private Paginacion paginacion;
		
		[WcfSerialization::DataMember(Name = "ListaPaginaAccion", IsRequired = false, Order = 0)]
		public ListaPaginaAccion ListaPaginaAccion
		{
		  get { return listaPaginaAccion; }
		  set { listaPaginaAccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Paginacion", IsRequired = false, Order = 1)]
		public Paginacion Paginacion
		{
		  get { return paginacion; }
		  set { paginacion = value; }
		}				
	}
}

