//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - PaginaTraductor
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "PaginaTraductor")]
	public partial class PaginaTraductor 
	{
		private int idPaginaTraductor;
		private int idLenguaje;
		private int idPagina;
		private string nombre;
		
		[WcfSerialization::DataMember(Name = "IdPaginaTraductor", IsRequired = false, Order = 0)]
		public int IdPaginaTraductor
		{
		  get { return idPaginaTraductor; }
		  set { idPaginaTraductor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdLenguaje", IsRequired = false, Order = 1)]
		public int IdLenguaje
		{
		  get { return idLenguaje; }
		  set { idLenguaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdPagina", IsRequired = false, Order = 2)]
		public int IdPagina
		{
		  get { return idPagina; }
		  set { idPagina = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 3)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
	}
}

