//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - PermisoPerfil
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "PermisoPerfil")]
	public partial class PermisoPerfil 
	{
		private int idPermisoPerfil;
		private Empresa empresa;
		private Aplicacion aplicacion;
		private Modulo modulo;
		private Pagina pagina;
		private Accion accion;
		private Rol rol;
		private int idEmpresa;
		private int idAplicacion;
		private int idModulo;
		private int idPagina;
		private int idAccion;
		private int idRol;
		
		[WcfSerialization::DataMember(Name = "IdPermisoPerfil", IsRequired = false, Order = 0)]
		public int IdPermisoPerfil
		{
		  get { return idPermisoPerfil; }
		  set { idPermisoPerfil = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Empresa", IsRequired = false, Order = 1)]
		public Empresa Empresa
		{
		  get { return empresa; }
		  set { empresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Aplicacion", IsRequired = false, Order = 2)]
		public Aplicacion Aplicacion
		{
		  get { return aplicacion; }
		  set { aplicacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Modulo", IsRequired = false, Order = 3)]
		public Modulo Modulo
		{
		  get { return modulo; }
		  set { modulo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Pagina", IsRequired = false, Order = 4)]
		public Pagina Pagina
		{
		  get { return pagina; }
		  set { pagina = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Accion", IsRequired = false, Order = 5)]
		public Accion Accion
		{
		  get { return accion; }
		  set { accion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Rol", IsRequired = false, Order = 6)]
		public Rol Rol
		{
		  get { return rol; }
		  set { rol = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdEmpresa", IsRequired = false, Order = 7)]
		public int IdEmpresa
		{
		  get { return idEmpresa; }
		  set { idEmpresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdAplicacion", IsRequired = false, Order = 8)]
		public int IdAplicacion
		{
		  get { return idAplicacion; }
		  set { idAplicacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdModulo", IsRequired = false, Order = 9)]
		public int IdModulo
		{
		  get { return idModulo; }
		  set { idModulo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdPagina", IsRequired = false, Order = 10)]
		public int IdPagina
		{
		  get { return idPagina; }
		  set { idPagina = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdAccion", IsRequired = false, Order = 11)]
		public int IdAccion
		{
		  get { return idAccion; }
		  set { idAccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdRol", IsRequired = false, Order = 12)]
		public int IdRol
		{
		  get { return idRol; }
		  set { idRol = value; }
		}				
	}
}

