//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - RecursiveTreeView
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "RecursiveTreeView")]
	public partial class RecursiveTreeView 
	{
		private string dataField;
		private string idField;
		private TreeViewAttribute attrField;
		private ListaRecursiveTreeView childrenField;
		
		[WcfSerialization::DataMember(Name = "data", IsRequired = false, Order = 0)]
		public string data
		{
		  get { return dataField; }
		  set { dataField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "id", IsRequired = false, Order = 1)]
		public string id
		{
		  get { return idField; }
		  set { idField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "attr", IsRequired = false, Order = 2)]
		public TreeViewAttribute attr
		{
		  get { return attrField; }
		  set { attrField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "children", IsRequired = false, Order = 3)]
		public ListaRecursiveTreeView children
		{
		  get { return childrenField; }
		  set { childrenField = value; }
		}				
	}
}

