//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Rol
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Rol")]
	public partial class Rol 
	{
		private int idRol;
		private bool siSuperAdmi;
		private string nombre;
		private Estado estado;
		private bool siRango;
		private System.DateTime fechaInicio;
		private System.DateTime fechaFin;
		private Aplicacion aplicacion;
		private Usuario usuario;
        private int idCentroAtencion;
        private string cadenaOperacion;
        private ListaOperacion listaOperacion;

        [WcfSerialization::DataMember(Name = "IdRol", IsRequired = false, Order = 0)]
		public int IdRol
		{
		  get { return idRol; }
		  set { idRol = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SiSuperAdmi", IsRequired = false, Order = 1)]
		public bool SiSuperAdmi
		{
		  get { return siSuperAdmi; }
		  set { siSuperAdmi = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 2)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 3)]
		public Estado Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SiRango", IsRequired = false, Order = 4)]
		public bool SiRango
		{
		  get { return siRango; }
		  set { siRango = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaInicio", IsRequired = false, Order = 5)]
		public System.DateTime FechaInicio
		{
		  get { return fechaInicio; }
		  set { fechaInicio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaFin", IsRequired = false, Order = 6)]
		public System.DateTime FechaFin
		{
		  get { return fechaFin; }
		  set { fechaFin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Aplicacion", IsRequired = false, Order = 7)]
		public Aplicacion Aplicacion
		{
		  get { return aplicacion; }
		  set { aplicacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Usuario", IsRequired = false, Order = 8)]
		public Usuario Usuario
		{
		  get { return usuario; }
		  set { usuario = value; }
		}

        [WcfSerialization::DataMember(Name = "IdCentroAtencion", IsRequired = false, Order = 9)]
        public int IdCentroAtencion
        {
            get { return idCentroAtencion; }
            set { idCentroAtencion = value; }
        }

        [WcfSerialization::DataMember(Name = "CadenaOperacion", IsRequired = false, Order = 10)]
        public string CadenaOperacion
        {
            get { return cadenaOperacion; }
            set { cadenaOperacion = value; }
        }

        [WcfSerialization::DataMember(Name = "ListaOperacion", IsRequired = false, Order = 11)]
        public ListaOperacion ListaOperacion
        {
            get { return listaOperacion; }
            set { listaOperacion = value; }
        }
    }
}

