//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - RolPaginacion
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "RolPaginacion")]
	public partial class RolPaginacion 
	{
		private Paginacion paginacion;
		private ListaRol listaRol;
		
		[WcfSerialization::DataMember(Name = "Paginacion", IsRequired = false, Order = 0)]
		public Paginacion Paginacion
		{
		  get { return paginacion; }
		  set { paginacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListaRol", IsRequired = false, Order = 1)]
		public ListaRol ListaRol
		{
		  get { return listaRol; }
		  set { listaRol = value; }
		}				
	}
}

