//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - RolTraductor
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "RolTraductor")]
	public partial class RolTraductor 
	{
		private int idRolTraductor;
		private int idLenguaje;
		private int idRol;
		private string nombre;
		private bool activo;
		
		[WcfSerialization::DataMember(Name = "IdRolTraductor", IsRequired = false, Order = 0)]
		public int IdRolTraductor
		{
		  get { return idRolTraductor; }
		  set { idRolTraductor = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdLenguaje", IsRequired = false, Order = 1)]
		public int IdLenguaje
		{
		  get { return idLenguaje; }
		  set { idLenguaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdRol", IsRequired = false, Order = 2)]
		public int IdRol
		{
		  get { return idRol; }
		  set { idRol = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 3)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Activo", IsRequired = false, Order = 4)]
		public bool Activo
		{
		  get { return activo; }
		  set { activo = value; }
		}				
	}
}

