//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - TreeviewHierarchyObject
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "TreeviewHierarchyObject")]
	public partial class TreeviewHierarchyObject 
	{
		private int id;
		private string nombre;
		private int idPadre;
		private int nivel;
		private int nivelPagina;
		private int idPaginaPadre;
		private bool check;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public int Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdPadre", IsRequired = false, Order = 2)]
		public int IdPadre
		{
		  get { return idPadre; }
		  set { idPadre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nivel", IsRequired = false, Order = 3)]
		public int Nivel
		{
		  get { return nivel; }
		  set { nivel = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NivelPagina", IsRequired = false, Order = 4)]
		public int NivelPagina
		{
		  get { return nivelPagina; }
		  set { nivelPagina = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdPaginaPadre", IsRequired = false, Order = 5)]
		public int IdPaginaPadre
		{
		  get { return idPaginaPadre; }
		  set { idPaginaPadre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Check", IsRequired = false, Order = 6)]
		public bool Check
		{
		  get { return check; }
		  set { check = value; }
		}				
	}
}

