//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Treeview
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Treeview")]
	public partial class Treeview 
	{
		private string id;
		private string parentId;
		private string dataField;
		private long level;
		private bool isChecKed;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public string Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ParentId", IsRequired = false, Order = 1)]
		public string ParentId
		{
		  get { return parentId; }
		  set { parentId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "data", IsRequired = false, Order = 2)]
		public string data
		{
		  get { return dataField; }
		  set { dataField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Level", IsRequired = false, Order = 3)]
		public long Level
		{
		  get { return level; }
		  set { level = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IsChecKed", IsRequired = false, Order = 4)]
		public bool IsChecKed
		{
		  get { return isChecKed; }
		  set { isChecKed = value; }
		}				
	}
}

