//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - TreeViewAttribute
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "TreeViewAttribute")]
	public partial class TreeViewAttribute 
	{
		private string idField;
		private bool selectedField;
		
		[WcfSerialization::DataMember(Name = "id", IsRequired = false, Order = 0)]
		public string id
		{
		  get { return idField; }
		  set { idField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "selected", IsRequired = false, Order = 1)]
		public bool selected
		{
		  get { return selectedField; }
		  set { selectedField = value; }
		}				
	}
}

