//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
    public partial class User
    {
        public int IdUsuario {get; set;}
        public string CodigoEmp { get; set; }
        public string EmailCoorporativo { get; set; }
        public string NombreApellido { get; set; }
        public string UserName { get; set; }
        public UsuarioTipo UsuarioTipo { get; set; }
        public ListaRol ListaRol { get; set; }
        public string DNI { get; set; }
        public int IdUnidadOrganica { get; set; }
        public string UnidadOrganicaDescripcionCorta { get; set; }
        public int IdAreaBU { get; set; }
        public string AreaBUDescripcionCorta { get; set; }
        public int IdCargo { get; set; }
        public string CargoDescripcionCorta { get; set; }
        public int IdComite { get; set; }
        public int Activo { get; set; }
    }
}

