//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Komatsu.Core.Seguridad.DataContracts.GeneratedCode;
using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - Usuario
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "Usuario")]
	public partial class Usuario 
	{
		private int idUsuario;
		private string codigoEmp;
		private string emailCoorporativo;
		private string nombreApellido;
		private Estado estado;
		private string userName;
		private UsuarioTipo usuarioTipo;
		private ListaRol listaRol;
		private string contentStyle;
		private string sexo;
		private string correo;
		private string correoBoleta;
		private string direccion;
		private System.DateTime fechaNacimiento;
		private Empresa empresa;
		private string dNI;
		private int idSociedad;
		private string sociedadDescripcionCorta;
		private int idAreaBU;
		private string areaBUDescripcionCorta;
		private int idCargo;
		private string cargoDescripcionCorta;
		private int idComite;
		private int activo;
        private int idAplicacion;
        private string password;
        private Cargo cargo;
        private Area area;
        private String idAreas;
        private bool cambiarPassword;
        private Empresa empresaRelacionada;

        [WcfSerialization::DataMember(Name = "IdUsuario", IsRequired = false, Order = 0)]
		public int IdUsuario
		{
		  get { return idUsuario; }
		  set { idUsuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodigoEmp", IsRequired = false, Order = 1)]
		public string CodigoEmp
		{
		  get { return codigoEmp; }
		  set { codigoEmp = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EmailCoorporativo", IsRequired = false, Order = 2)]
		public string EmailCoorporativo
		{
		  get { return emailCoorporativo; }
		  set { emailCoorporativo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NombreApellido", IsRequired = false, Order = 3)]
		public string NombreApellido
		{
		  get { return nombreApellido; }
		  set { nombreApellido = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 4)]
		public Estado Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UserName", IsRequired = false, Order = 5)]
		public string UserName
		{
		  get { return userName; }
		  set { userName = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UsuarioTipo", IsRequired = false, Order = 6)]
		public UsuarioTipo UsuarioTipo
		{
		  get { return usuarioTipo; }
		  set { usuarioTipo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ListaRol", IsRequired = false, Order = 7)]
		public ListaRol ListaRol
		{
		  get { return listaRol; }
		  set { listaRol = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ContentStyle", IsRequired = false, Order = 8)]
		public string ContentStyle
		{
		  get { return contentStyle; }
		  set { contentStyle = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Sexo", IsRequired = false, Order = 9)]
		public string Sexo
		{
		  get { return sexo; }
		  set { sexo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Correo", IsRequired = false, Order = 10)]
		public string Correo
		{
		  get { return correo; }
		  set { correo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CorreoBoleta", IsRequired = false, Order = 11)]
		public string CorreoBoleta
		{
		  get { return correoBoleta; }
		  set { correoBoleta = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Direccion", IsRequired = false, Order = 12)]
		public string Direccion
		{
		  get { return direccion; }
		  set { direccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaNacimiento", IsRequired = false, Order = 13)]
		public System.DateTime FechaNacimiento
		{
		  get { return fechaNacimiento; }
		  set { fechaNacimiento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Empresa", IsRequired = false, Order = 14)]
		public Empresa Empresa
		{
		  get { return empresa; }
		  set { empresa = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DNI", IsRequired = false, Order = 15)]
		public string DNI
		{
		  get { return dNI; }
		  set { dNI = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdSociedad", IsRequired = false, Order = 16)]
		public int IdSociedad
		{
		  get { return idSociedad; }
		  set { idSociedad = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "SociedadDescripcionCorta", IsRequired = false, Order = 17)]
		public string SociedadDescripcionCorta
		{
		  get { return sociedadDescripcionCorta; }
		  set { sociedadDescripcionCorta = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdAreaBU", IsRequired = false, Order = 18)]
		public int IdAreaBU
		{
		  get { return idAreaBU; }
		  set { idAreaBU = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AreaBUDescripcionCorta", IsRequired = false, Order = 19)]
		public string AreaBUDescripcionCorta
		{
		  get { return areaBUDescripcionCorta; }
		  set { areaBUDescripcionCorta = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdCargo", IsRequired = false, Order = 20)]
		public int IdCargo
		{
		  get { return idCargo; }
		  set { idCargo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CargoDescripcionCorta", IsRequired = false, Order = 21)]
		public string CargoDescripcionCorta
		{
		  get { return cargoDescripcionCorta; }
		  set { cargoDescripcionCorta = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdComite", IsRequired = false, Order = 22)]
		public int IdComite
		{
		  get { return idComite; }
		  set { idComite = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Activo", IsRequired = false, Order = 23)]
		public int Activo
		{
		  get { return activo; }
		  set { activo = value; }
		}

        [WcfSerialization::DataMember(Name = "IdAplicacion", IsRequired = false, Order = 22)]
        public int IdAplicacion
        {
            get { return idAplicacion; }
            set { idAplicacion = value; }
        }

        [WcfSerialization::DataMember(Name = "Password", IsRequired = false, Order = 23)]
        public String Password
        {
            get { return password; }
            set { password = value; }
        }


        [WcfSerialization::DataMember(Name = "Cargo", IsRequired = false, Order = 24)]
        public Cargo Cargo
        {
            get { return cargo; }
            set { cargo = value; }
        }


        [WcfSerialization::DataMember(Name = "Area", IsRequired = false, Order = 25)]
        public Area Area
        {
            get { return area; }
            set { area = value; }
        }

        [WcfSerialization::DataMember(Name = "IdAreas", IsRequired = false, Order = 26)]
        public string IdAreas
        {
            get { return idAreas; }
            set { idAreas = value; }
        }

        [WcfSerialization::DataMember(Name = "CambiarPassword", IsRequired = false, Order = 27)]
        public bool CambiarPassword
        {
            get { return cambiarPassword; }
            set { cambiarPassword = value; }
        }

        [WcfSerialization::DataMember(Name = "EmpresaRelacionada", IsRequired = false, Order = 28)]
        public Empresa EmpresaRelacionada
        {
            get { return empresaRelacionada; }
            set { empresaRelacionada = value; }
        }
    }
}

