//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - UsuarioRol
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "UsuarioRol")]
	public partial class UsuarioRol 
	{
		private int idUsuario;
		private int idRol;
		private Usuario usuario;
		private Rol rol;
		
		[WcfSerialization::DataMember(Name = "IdUsuario", IsRequired = false, Order = 0)]
		public int IdUsuario
		{
		  get { return idUsuario; }
		  set { idUsuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdRol", IsRequired = false, Order = 1)]
		public int IdRol
		{
		  get { return idRol; }
		  set { idRol = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Usuario", IsRequired = false, Order = 2)]
		public Usuario Usuario
		{
		  get { return usuario; }
		  set { usuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Rol", IsRequired = false, Order = 3)]
		public Rol Rol
		{
		  get { return rol; }
		  set { rol = value; }
		}				
	}
}

