//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Komatsu.Core.Seguridad.DataContracts
{
	/// <summary>
	/// Data Contract Class - UsuarioTipo
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://komatsu.core.seguridad.model/2013/dckomatsuseguridad", Name = "UsuarioTipo")]
	public partial class UsuarioTipo 
	{
		private int idUsuarioTipo;
		private string nombre;
		
		[WcfSerialization::DataMember(Name = "IdUsuarioTipo", IsRequired = false, Order = 0)]
		public int IdUsuarioTipo
		{
		  get { return idUsuarioTipo; }
		  set { idUsuarioTipo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
	}
}

